/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public class Age {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Age(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Age obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_Age(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Age(Age source) {
    this(imebraJNI.new_Age__SWIG_0(Age.getCPtr(source), source), true);
  }

  public Age(long initialAge, ageUnit_t initialUnits) {
    this(imebraJNI.new_Age__SWIG_1(initialAge, initialUnits.swigValue()), true);
  }

  public double getYears() {
    return imebraJNI.Age_getYears(swigCPtr, this);
  }

  public long getAgeValue() {
    return imebraJNI.Age_getAgeValue(swigCPtr, this);
  }

  public ageUnit_t getAgeUnits() {
    return ageUnit_t.swigToEnum(imebraJNI.Age_getAgeUnits(swigCPtr, this));
  }

}
