/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public class AssociationSCU extends AssociationBase {
  private transient long swigCPtr;

  protected AssociationSCU(long cPtr, boolean cMemoryOwn) {
    super(imebraJNI.AssociationSCU_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AssociationSCU obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_AssociationSCU(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public AssociationSCU(String thisAET, String otherAET, long invokedOperations, long performedOperations, PresentationContexts presentationContexts, StreamReader pInput, StreamWriter pOutput, long dimseTimeoutSeconds) {
    this(imebraJNI.new_AssociationSCU__SWIG_0(thisAET, otherAET, invokedOperations, performedOperations, PresentationContexts.getCPtr(presentationContexts), presentationContexts, StreamReader.getCPtr(pInput), pInput, StreamWriter.getCPtr(pOutput), pOutput, dimseTimeoutSeconds), true);
  }

  public AssociationSCU(AssociationSCU source) {
    this(imebraJNI.new_AssociationSCU__SWIG_1(AssociationSCU.getCPtr(source), source), true);
  }

}
