/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public class AssociationSCP extends AssociationBase {
  private transient long swigCPtr;

  protected AssociationSCP(long cPtr, boolean cMemoryOwn) {
    super(imebraJNI.AssociationSCP_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AssociationSCP obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_AssociationSCP(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public AssociationSCP(String thisAET, long invokedOperations, long performedOperations, PresentationContexts presentationContexts, StreamReader pInput, StreamWriter pOutput, long dimseTimeoutSeconds, long artimTimeoutSeconds) {
    this(imebraJNI.new_AssociationSCP__SWIG_0(thisAET, invokedOperations, performedOperations, PresentationContexts.getCPtr(presentationContexts), presentationContexts, StreamReader.getCPtr(pInput), pInput, StreamWriter.getCPtr(pOutput), pOutput, dimseTimeoutSeconds, artimTimeoutSeconds), true);
  }

  public AssociationSCP(AssociationSCP source) {
    this(imebraJNI.new_AssociationSCP__SWIG_1(AssociationSCP.getCPtr(source), source), true);
  }

}
