/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public class AssociationMessage {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected AssociationMessage(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AssociationMessage obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_AssociationMessage(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public AssociationMessage(AssociationMessage source) {
    this(imebraJNI.new_AssociationMessage(AssociationMessage.getCPtr(source), source), true);
  }

  public String getAbstractSyntax() {
    return imebraJNI.AssociationMessage_getAbstractSyntax(swigCPtr, this);
  }

  public DataSet getCommand() {
    return new DataSet(imebraJNI.AssociationMessage_getCommand(swigCPtr, this), true);
  }

  public DataSet getPayload() {
    return new DataSet(imebraJNI.AssociationMessage_getPayload(swigCPtr, this), true);
  }

  public boolean hasPayload() {
    return imebraJNI.AssociationMessage_hasPayload(swigCPtr, this);
  }

}
