/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public class CCancelCommand extends DimseCommand {
  private transient long swigCPtr;

  protected CCancelCommand(long cPtr, boolean cMemoryOwn) {
    super(imebraJNI.CCancelCommand_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CCancelCommand obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_CCancelCommand(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public CCancelCommand(String abstractSyntax, int messageID, dimseCommandPriority_t priority, int cancelMessageID) {
    this(imebraJNI.new_CCancelCommand__SWIG_0(abstractSyntax, messageID, priority.swigValue(), cancelMessageID), true);
  }

  public CCancelCommand(CCancelCommand source) {
    this(imebraJNI.new_CCancelCommand__SWIG_1(CCancelCommand.getCPtr(source), source), true);
  }

  public int getCancelMessageID() {
    return imebraJNI.CCancelCommand_getCancelMessageID(swigCPtr, this);
  }

}
