/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public class CEchoCommand extends DimseCommand {
  private transient long swigCPtr;

  protected CEchoCommand(long cPtr, boolean cMemoryOwn) {
    super(imebraJNI.CEchoCommand_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CEchoCommand obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_CEchoCommand(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public CEchoCommand(String abstractSyntax, int messageID, dimseCommandPriority_t priority, String affectedSopClassUid) {
    this(imebraJNI.new_CEchoCommand__SWIG_0(abstractSyntax, messageID, priority.swigValue(), affectedSopClassUid), true);
  }

  public CEchoCommand(CEchoCommand source) {
    this(imebraJNI.new_CEchoCommand__SWIG_1(CEchoCommand.getCPtr(source), source), true);
  }

}
