/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public class CEchoResponse extends DimseResponse {
  private transient long swigCPtr;

  protected CEchoResponse(long cPtr, boolean cMemoryOwn) {
    super(imebraJNI.CEchoResponse_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CEchoResponse obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_CEchoResponse(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public CEchoResponse(CEchoCommand receivedCommand, dimseStatusCode_t responseCode) {
    this(imebraJNI.new_CEchoResponse__SWIG_0(CEchoCommand.getCPtr(receivedCommand), receivedCommand, responseCode.swigValue()), true);
  }

  public CEchoResponse(CEchoResponse source) {
    this(imebraJNI.new_CEchoResponse__SWIG_1(CEchoResponse.getCPtr(source), source), true);
  }

}
