/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public class CStoreCommand extends DimseCommand {
  private transient long swigCPtr;

  protected CStoreCommand(long cPtr, boolean cMemoryOwn) {
    super(imebraJNI.CStoreCommand_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CStoreCommand obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_CStoreCommand(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public CStoreCommand(String abstractSyntax, int messageID, dimseCommandPriority_t priority, String affectedSopClassUid, String affectedSopInstanceUid, String originatorAET, int originatorMessageID, DataSet payload) {
    this(imebraJNI.new_CStoreCommand__SWIG_0(abstractSyntax, messageID, priority.swigValue(), affectedSopClassUid, affectedSopInstanceUid, originatorAET, originatorMessageID, DataSet.getCPtr(payload), payload), true);
  }

  public CStoreCommand(CStoreCommand source) {
    this(imebraJNI.new_CStoreCommand__SWIG_1(CStoreCommand.getCPtr(source), source), true);
  }

  public String getOriginatorAET() {
    return imebraJNI.CStoreCommand_getOriginatorAET(swigCPtr, this);
  }

  public int getOriginatorMessageID() {
    return imebraJNI.CStoreCommand_getOriginatorMessageID(swigCPtr, this);
  }

}
