/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public class CStoreResponse extends DimseResponse {
  private transient long swigCPtr;

  protected CStoreResponse(long cPtr, boolean cMemoryOwn) {
    super(imebraJNI.CStoreResponse_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CStoreResponse obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_CStoreResponse(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public CStoreResponse(CStoreCommand command, dimseStatusCode_t responseCode) {
    this(imebraJNI.new_CStoreResponse__SWIG_0(CStoreCommand.getCPtr(command), command, responseCode.swigValue()), true);
  }

  public CStoreResponse(CStoreResponse source) {
    this(imebraJNI.new_CStoreResponse__SWIG_1(CStoreResponse.getCPtr(source), source), true);
  }

}
