/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public class Date {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Date(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Date obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_Date(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Date(Date source) {
    this(imebraJNI.new_Date__SWIG_0(Date.getCPtr(source), source), true);
  }

  public Date(long initialYear, long initialMonth, long initialDay, long initialHour, long initialMinutes, long initialSeconds, long initialNanoseconds, int initialOffsetHours, int initialOffsetMinutes) {
    this(imebraJNI.new_Date__SWIG_1(initialYear, initialMonth, initialDay, initialHour, initialMinutes, initialSeconds, initialNanoseconds, initialOffsetHours, initialOffsetMinutes), true);
  }

  public long getYear() {
    return imebraJNI.Date_getYear(swigCPtr, this);
  }

  public long getMonth() {
    return imebraJNI.Date_getMonth(swigCPtr, this);
  }

  public long getDay() {
    return imebraJNI.Date_getDay(swigCPtr, this);
  }

  public long getHour() {
    return imebraJNI.Date_getHour(swigCPtr, this);
  }

  public long getMinutes() {
    return imebraJNI.Date_getMinutes(swigCPtr, this);
  }

  public long getSeconds() {
    return imebraJNI.Date_getSeconds(swigCPtr, this);
  }

  public long getNanoseconds() {
    return imebraJNI.Date_getNanoseconds(swigCPtr, this);
  }

  public int getOffsetHours() {
    return imebraJNI.Date_getOffsetHours(swigCPtr, this);
  }

  public int getOffsetMinutes() {
    return imebraJNI.Date_getOffsetMinutes(swigCPtr, this);
  }

}
