/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public class DicomDir {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DicomDir(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DicomDir obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_DicomDir(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DicomDir(DataSet fromDataSet) {
    this(imebraJNI.new_DicomDir__SWIG_0(DataSet.getCPtr(fromDataSet), fromDataSet), true);
  }

  public DicomDir(DicomDir source) {
    this(imebraJNI.new_DicomDir__SWIG_1(DicomDir.getCPtr(source), source), true);
  }

  public boolean hasRootEntry() {
    return imebraJNI.DicomDir_hasRootEntry(swigCPtr, this);
  }

  public DicomDirEntry getFirstRootEntry() {
    return new DicomDirEntry(imebraJNI.DicomDir_getFirstRootEntry(swigCPtr, this), true);
  }

}
