/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public enum dimseStatusCode_t {
  success(imebraJNI.dimseStatusCode_t_success_get()),
  unsupportedOptionalAttributes(imebraJNI.dimseStatusCode_t_unsupportedOptionalAttributes_get()),
  cannotUpdateperformedProcedureStepObject(imebraJNI.dimseStatusCode_t_cannotUpdateperformedProcedureStepObject_get()),
  unsupportedSOPClass(imebraJNI.dimseStatusCode_t_unsupportedSOPClass_get()),
  outOfResources(imebraJNI.dimseStatusCode_t_outOfResources_get()),
  outOfResourcesCannotCalculateNumberOfMatches(imebraJNI.dimseStatusCode_t_outOfResourcesCannotCalculateNumberOfMatches_get()),
  outOfResourcesCannotPerformSubOperations(imebraJNI.dimseStatusCode_t_outOfResourcesCannotPerformSubOperations_get()),
  moveDestinationUnknown(imebraJNI.dimseStatusCode_t_moveDestinationUnknown_get()),
  identifierDoesNotMatchSOPClass(imebraJNI.dimseStatusCode_t_identifierDoesNotMatchSOPClass_get()),
  subOperationCompletedWithErrors(imebraJNI.dimseStatusCode_t_subOperationCompletedWithErrors_get()),
  elementDiscarded(imebraJNI.dimseStatusCode_t_elementDiscarded_get()),
  datasetDoesNotMatchSOPClass(imebraJNI.dimseStatusCode_t_datasetDoesNotMatchSOPClass_get()),
  UPSAlreadyCanceled(imebraJNI.dimseStatusCode_t_UPSAlreadyCanceled_get()),
  coercedInvalidValuesToValidValues(imebraJNI.dimseStatusCode_t_coercedInvalidValuesToValidValues_get()),
  UPSStateAlreadyCompleted(imebraJNI.dimseStatusCode_t_UPSStateAlreadyCompleted_get()),
  unableToProcess(imebraJNI.dimseStatusCode_t_unableToProcess_get()),
  moreThanOneMatchFound(imebraJNI.dimseStatusCode_t_moreThanOneMatchFound_get()),
  CannotSupportRequestedTemplate(imebraJNI.dimseStatusCode_t_CannotSupportRequestedTemplate_get()),
  UPSNotUpdated(imebraJNI.dimseStatusCode_t_UPSNotUpdated_get()),
  transactionUIDNotProvided(imebraJNI.dimseStatusCode_t_transactionUIDNotProvided_get()),
  UPSAlreadyInProgress(imebraJNI.dimseStatusCode_t_UPSAlreadyInProgress_get()),
  canScheduleOnlyWithNCreate(imebraJNI.dimseStatusCode_t_canScheduleOnlyWithNCreate_get()),
  UPSCannotChangeState(imebraJNI.dimseStatusCode_t_UPSCannotChangeState_get()),
  instanceUIDDoesNotExist(imebraJNI.dimseStatusCode_t_instanceUIDDoesNotExist_get()),
  unknownAETitle(imebraJNI.dimseStatusCode_t_unknownAETitle_get()),
  UPSNotSchedule(imebraJNI.dimseStatusCode_t_UPSNotSchedule_get()),
  UPSNotInProgress(imebraJNI.dimseStatusCode_t_UPSNotInProgress_get()),
  UPSAlreadyCompleted(imebraJNI.dimseStatusCode_t_UPSAlreadyCompleted_get()),
  performerCannotBeContacted(imebraJNI.dimseStatusCode_t_performerCannotBeContacted_get()),
  performerDoesNotCancel(imebraJNI.dimseStatusCode_t_performerDoesNotCancel_get()),
  unappropriateActionForInstance(imebraJNI.dimseStatusCode_t_unappropriateActionForInstance_get()),
  SCPDoesNotSupportEventReports(imebraJNI.dimseStatusCode_t_SCPDoesNotSupportEventReports_get()),
  canceled(imebraJNI.dimseStatusCode_t_canceled_get()),
  pending(imebraJNI.dimseStatusCode_t_pending_get()),
  pendingWithWarnings(imebraJNI.dimseStatusCode_t_pendingWithWarnings_get());

  public final int swigValue() {
    return swigValue;
  }

  public static dimseStatusCode_t swigToEnum(int swigValue) {
    dimseStatusCode_t[] swigValues = dimseStatusCode_t.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (dimseStatusCode_t swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + dimseStatusCode_t.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private dimseStatusCode_t() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private dimseStatusCode_t(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private dimseStatusCode_t(dimseStatusCode_t swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

