/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public class DimseCommandBase {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DimseCommandBase(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DimseCommandBase obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_DimseCommandBase(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DimseCommandBase(DimseCommandBase source) {
    this(imebraJNI.new_DimseCommandBase(DimseCommandBase.getCPtr(source), source), true);
  }

  public DataSet getCommandDataSet() {
    return new DataSet(imebraJNI.DimseCommandBase_getCommandDataSet(swigCPtr, this), true);
  }

  public DataSet getPayloadDataSet() {
    return new DataSet(imebraJNI.DimseCommandBase_getPayloadDataSet(swigCPtr, this), true);
  }

  public String getAbstractSyntax() {
    return imebraJNI.DimseCommandBase_getAbstractSyntax(swigCPtr, this);
  }

  public String getAffectedSopInstanceUid() {
    return imebraJNI.DimseCommandBase_getAffectedSopInstanceUid(swigCPtr, this);
  }

  public String getAffectedSopClassUid() {
    return imebraJNI.DimseCommandBase_getAffectedSopClassUid(swigCPtr, this);
  }

  public String getRequestedSopInstanceUid() {
    return imebraJNI.DimseCommandBase_getRequestedSopInstanceUid(swigCPtr, this);
  }

  public String getRequestedSopClassUid() {
    return imebraJNI.DimseCommandBase_getRequestedSopClassUid(swigCPtr, this);
  }

}
