/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public enum dimseCommandType_t {
  cStore(imebraJNI.dimseCommandType_t_cStore_get()),
  cGet(imebraJNI.dimseCommandType_t_cGet_get()),
  cFind(imebraJNI.dimseCommandType_t_cFind_get()),
  cMove(imebraJNI.dimseCommandType_t_cMove_get()),
  cCancel(imebraJNI.dimseCommandType_t_cCancel_get()),
  cEcho(imebraJNI.dimseCommandType_t_cEcho_get()),
  nEventReport(imebraJNI.dimseCommandType_t_nEventReport_get()),
  nGet(imebraJNI.dimseCommandType_t_nGet_get()),
  nSet(imebraJNI.dimseCommandType_t_nSet_get()),
  nAction(imebraJNI.dimseCommandType_t_nAction_get()),
  nCreate(imebraJNI.dimseCommandType_t_nCreate_get()),
  nDelete(imebraJNI.dimseCommandType_t_nDelete_get()),
  response(imebraJNI.dimseCommandType_t_response_get());

  public final int swigValue() {
    return swigValue;
  }

  public static dimseCommandType_t swigToEnum(int swigValue) {
    dimseCommandType_t[] swigValues = dimseCommandType_t.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (dimseCommandType_t swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + dimseCommandType_t.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private dimseCommandType_t() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private dimseCommandType_t(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private dimseCommandType_t(dimseCommandType_t swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

