/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public class DimseService {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DimseService(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DimseService obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_DimseService(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DimseService(AssociationBase association) {
    this(imebraJNI.new_DimseService__SWIG_0(AssociationBase.getCPtr(association), association), true);
  }

  public DimseService(DimseService source) {
    this(imebraJNI.new_DimseService__SWIG_1(DimseService.getCPtr(source), source), true);
  }

  public String getTransferSyntax(String abstractSyntax) {
    return imebraJNI.DimseService_getTransferSyntax(swigCPtr, this, abstractSyntax);
  }

  public int getNextCommandID() {
    return imebraJNI.DimseService_getNextCommandID(swigCPtr, this);
  }

  public DimseCommand getCommand() {
    return new DimseCommand(imebraJNI.DimseService_getCommand(swigCPtr, this), true);
  }

  public void sendCommandOrResponse(DimseCommandBase command) {
    imebraJNI.DimseService_sendCommandOrResponse(swigCPtr, this, DimseCommandBase.getCPtr(command), command);
  }

  public CStoreResponse getCStoreResponse(CStoreCommand command) {
    return new CStoreResponse(imebraJNI.DimseService_getCStoreResponse(swigCPtr, this, CStoreCommand.getCPtr(command), command), true);
  }

  public CGetResponse getCGetResponse(CGetCommand command) {
    return new CGetResponse(imebraJNI.DimseService_getCGetResponse(swigCPtr, this, CGetCommand.getCPtr(command), command), true);
  }

  public CFindResponse getCFindResponse(CFindCommand command) {
    return new CFindResponse(imebraJNI.DimseService_getCFindResponse(swigCPtr, this, CFindCommand.getCPtr(command), command), true);
  }

  public CMoveResponse getCMoveResponse(CMoveCommand command) {
    return new CMoveResponse(imebraJNI.DimseService_getCMoveResponse(swigCPtr, this, CMoveCommand.getCPtr(command), command), true);
  }

  public CEchoResponse getCEchoResponse(CEchoCommand command) {
    return new CEchoResponse(imebraJNI.DimseService_getCEchoResponse(swigCPtr, this, CEchoCommand.getCPtr(command), command), true);
  }

  public NEventReportResponse getNEventReportResponse(NEventReportCommand command) {
    return new NEventReportResponse(imebraJNI.DimseService_getNEventReportResponse(swigCPtr, this, NEventReportCommand.getCPtr(command), command), true);
  }

  public NGetResponse getNGetResponse(NGetCommand command) {
    return new NGetResponse(imebraJNI.DimseService_getNGetResponse(swigCPtr, this, NGetCommand.getCPtr(command), command), true);
  }

  public NSetResponse getNSetResponse(NSetCommand command) {
    return new NSetResponse(imebraJNI.DimseService_getNSetResponse(swigCPtr, this, NSetCommand.getCPtr(command), command), true);
  }

  public NActionResponse getNActionResponse(NActionCommand command) {
    return new NActionResponse(imebraJNI.DimseService_getNActionResponse(swigCPtr, this, NActionCommand.getCPtr(command), command), true);
  }

  public NCreateResponse getNCreateResponse(NCreateCommand command) {
    return new NCreateResponse(imebraJNI.DimseService_getNCreateResponse(swigCPtr, this, NCreateCommand.getCPtr(command), command), true);
  }

  public NDeleteResponse getNDeleteResponse(NDeleteCommand command) {
    return new NDeleteResponse(imebraJNI.DimseService_getNDeleteResponse(swigCPtr, this, NDeleteCommand.getCPtr(command), command), true);
  }

}
