/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public class DimseCommand extends DimseCommandBase {
  private transient long swigCPtr;

  protected DimseCommand(long cPtr, boolean cMemoryOwn) {
    super(imebraJNI.DimseCommand_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DimseCommand obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_DimseCommand(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public DimseCommand(DimseCommand source) {
    this(imebraJNI.new_DimseCommand(DimseCommand.getCPtr(source), source), true);
  }

  public int getID() {
    return imebraJNI.DimseCommand_getID(swigCPtr, this);
  }

  public dimseCommandType_t getCommandType() {
    return dimseCommandType_t.swigToEnum(imebraJNI.DimseCommand_getCommandType(swigCPtr, this));
  }

  public CStoreCommand getAsCStoreCommand() {
    return new CStoreCommand(imebraJNI.DimseCommand_getAsCStoreCommand(swigCPtr, this), true);
  }

  public CMoveCommand getAsCMoveCommand() {
    return new CMoveCommand(imebraJNI.DimseCommand_getAsCMoveCommand(swigCPtr, this), true);
  }

  public CGetCommand getAsCGetCommand() {
    return new CGetCommand(imebraJNI.DimseCommand_getAsCGetCommand(swigCPtr, this), true);
  }

  public CFindCommand getAsCFindCommand() {
    return new CFindCommand(imebraJNI.DimseCommand_getAsCFindCommand(swigCPtr, this), true);
  }

  public CEchoCommand getAsCEchoCommand() {
    return new CEchoCommand(imebraJNI.DimseCommand_getAsCEchoCommand(swigCPtr, this), true);
  }

  public CCancelCommand getAsCCancelCommand() {
    return new CCancelCommand(imebraJNI.DimseCommand_getAsCCancelCommand(swigCPtr, this), true);
  }

  public NActionCommand getAsNActionCommand() {
    return new NActionCommand(imebraJNI.DimseCommand_getAsNActionCommand(swigCPtr, this), true);
  }

  public NEventReportCommand getAsNEventReportCommand() {
    return new NEventReportCommand(imebraJNI.DimseCommand_getAsNEventReportCommand(swigCPtr, this), true);
  }

  public NCreateCommand getAsNCreateCommand() {
    return new NCreateCommand(imebraJNI.DimseCommand_getAsNCreateCommand(swigCPtr, this), true);
  }

  public NDeleteCommand getAsNDeleteCommand() {
    return new NDeleteCommand(imebraJNI.DimseCommand_getAsNDeleteCommand(swigCPtr, this), true);
  }

  public NSetCommand getAsNSetCommand() {
    return new NSetCommand(imebraJNI.DimseCommand_getAsNSetCommand(swigCPtr, this), true);
  }

  public NGetCommand getAsNGetCommand() {
    return new NGetCommand(imebraJNI.DimseCommand_getAsNGetCommand(swigCPtr, this), true);
  }

}
