/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public class FileStreamInput extends BaseStreamInput {
  private transient long swigCPtr;

  protected FileStreamInput(long cPtr, boolean cMemoryOwn) {
    super(imebraJNI.FileStreamInput_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FileStreamInput obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_FileStreamInput(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public FileStreamInput(String name) {
    this(imebraJNI.new_FileStreamInput__SWIG_0(name), true);
  }

  public FileStreamInput(FileStreamInput source) {
    this(imebraJNI.new_FileStreamInput__SWIG_1(FileStreamInput.getCPtr(source), source), true);
  }

}
