/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public class Image {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Image(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Image obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_Image(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Image(Image source) {
    this(imebraJNI.new_Image(Image.getCPtr(source), source), true);
  }

  public long getWidth() {
    return imebraJNI.Image_getWidth(swigCPtr, this);
  }

  public long getHeight() {
    return imebraJNI.Image_getHeight(swigCPtr, this);
  }

  public ReadingDataHandlerNumeric getReadingDataHandler() {
    return new ReadingDataHandlerNumeric(imebraJNI.Image_getReadingDataHandler(swigCPtr, this), true);
  }

  public String getColorSpace() {
    return imebraJNI.Image_getColorSpace(swigCPtr, this);
  }

  public long getChannelsNumber() {
    return imebraJNI.Image_getChannelsNumber(swigCPtr, this);
  }

  public bitDepth_t getDepth() {
    return bitDepth_t.swigToEnum(imebraJNI.Image_getDepth(swigCPtr, this));
  }

  public long getHighBit() {
    return imebraJNI.Image_getHighBit(swigCPtr, this);
  }

}
