/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public class imebra {
  public static String getUidVerificationSOPClass_1_2_840_10008_1_1() {
    return imebraJNI.uidVerificationSOPClass_1_2_840_10008_1_1_get();
  }

  public static String getUidImplicitVRLittleEndian_1_2_840_10008_1_2() {
    return imebraJNI.uidImplicitVRLittleEndian_1_2_840_10008_1_2_get();
  }

  public static String getUidExplicitVRLittleEndian_1_2_840_10008_1_2_1() {
    return imebraJNI.uidExplicitVRLittleEndian_1_2_840_10008_1_2_1_get();
  }

  public static String getUidDeflatedExplicitVRLittleEndian_1_2_840_10008_1_2_1_99() {
    return imebraJNI.uidDeflatedExplicitVRLittleEndian_1_2_840_10008_1_2_1_99_get();
  }

  public static String getUidExplicitVRBigEndian_1_2_840_10008_1_2_2() {
    return imebraJNI.uidExplicitVRBigEndian_1_2_840_10008_1_2_2_get();
  }

  public static String getUidJPEGBaselineProcess1_1_2_840_10008_1_2_4_50() {
    return imebraJNI.uidJPEGBaselineProcess1_1_2_840_10008_1_2_4_50_get();
  }

  public static String getUidJPEGExtendedProcess2_4_1_2_840_10008_1_2_4_51() {
    return imebraJNI.uidJPEGExtendedProcess2_4_1_2_840_10008_1_2_4_51_get();
  }

  public static String getUidJPEGExtendedProcess3_5_1_2_840_10008_1_2_4_52() {
    return imebraJNI.uidJPEGExtendedProcess3_5_1_2_840_10008_1_2_4_52_get();
  }

  public static String getUidJPEGSpectralSelectionNonHierarchicalProcess6_8_1_2_840_10008_1_2_4_53() {
    return imebraJNI.uidJPEGSpectralSelectionNonHierarchicalProcess6_8_1_2_840_10008_1_2_4_53_get();
  }

  public static String getUidJPEGSpectralSelectionNonHierarchicalProcess7_9_1_2_840_10008_1_2_4_54() {
    return imebraJNI.uidJPEGSpectralSelectionNonHierarchicalProcess7_9_1_2_840_10008_1_2_4_54_get();
  }

  public static String getUidJPEGFullProgressionNonHierarchicalProcess10_12_1_2_840_10008_1_2_4_55() {
    return imebraJNI.uidJPEGFullProgressionNonHierarchicalProcess10_12_1_2_840_10008_1_2_4_55_get();
  }

  public static String getUidJPEGFullProgressionNonHierarchicalProcess11_13_1_2_840_10008_1_2_4_56() {
    return imebraJNI.uidJPEGFullProgressionNonHierarchicalProcess11_13_1_2_840_10008_1_2_4_56_get();
  }

  public static String getUidJPEGLosslessNonHierarchicalProcess14_1_2_840_10008_1_2_4_57() {
    return imebraJNI.uidJPEGLosslessNonHierarchicalProcess14_1_2_840_10008_1_2_4_57_get();
  }

  public static String getUidJPEGLosslessNonHierarchicalProcess15_1_2_840_10008_1_2_4_58() {
    return imebraJNI.uidJPEGLosslessNonHierarchicalProcess15_1_2_840_10008_1_2_4_58_get();
  }

  public static String getUidJPEGExtendedHierarchicalProcess16_18_1_2_840_10008_1_2_4_59() {
    return imebraJNI.uidJPEGExtendedHierarchicalProcess16_18_1_2_840_10008_1_2_4_59_get();
  }

  public static String getUidJPEGExtendedHierarchicalProcess17_19_1_2_840_10008_1_2_4_60() {
    return imebraJNI.uidJPEGExtendedHierarchicalProcess17_19_1_2_840_10008_1_2_4_60_get();
  }

  public static String getUidJPEGSpectralSelectionHierarchicalProcess20_22_1_2_840_10008_1_2_4_61() {
    return imebraJNI.uidJPEGSpectralSelectionHierarchicalProcess20_22_1_2_840_10008_1_2_4_61_get();
  }

  public static String getUidJPEGSpectralSelectionHierarchicalProcess21_23_1_2_840_10008_1_2_4_62() {
    return imebraJNI.uidJPEGSpectralSelectionHierarchicalProcess21_23_1_2_840_10008_1_2_4_62_get();
  }

  public static String getUidJPEGFullProgressionHierarchicalProcess24_26_1_2_840_10008_1_2_4_63() {
    return imebraJNI.uidJPEGFullProgressionHierarchicalProcess24_26_1_2_840_10008_1_2_4_63_get();
  }

  public static String getUidJPEGFullProgressionHierarchicalProcess25_27_1_2_840_10008_1_2_4_64() {
    return imebraJNI.uidJPEGFullProgressionHierarchicalProcess25_27_1_2_840_10008_1_2_4_64_get();
  }

  public static String getUidJPEGLosslessHierarchicalProcess28_1_2_840_10008_1_2_4_65() {
    return imebraJNI.uidJPEGLosslessHierarchicalProcess28_1_2_840_10008_1_2_4_65_get();
  }

  public static String getUidJPEGLosslessHierarchicalProcess29_1_2_840_10008_1_2_4_66() {
    return imebraJNI.uidJPEGLosslessHierarchicalProcess29_1_2_840_10008_1_2_4_66_get();
  }

  public static String getUidJPEGLosslessNonHierarchicalFirstOrderPredictionProcess14SelectionValue1_1_2_840_10008_1_2_4_70() {
    return imebraJNI.uidJPEGLosslessNonHierarchicalFirstOrderPredictionProcess14SelectionValue1_1_2_840_10008_1_2_4_70_get();
  }

  public static String getUidJPEGLSLosslessImageCompression_1_2_840_10008_1_2_4_80() {
    return imebraJNI.uidJPEGLSLosslessImageCompression_1_2_840_10008_1_2_4_80_get();
  }

  public static String getUidJPEGLSLossyNearLosslessImageCompression_1_2_840_10008_1_2_4_81() {
    return imebraJNI.uidJPEGLSLossyNearLosslessImageCompression_1_2_840_10008_1_2_4_81_get();
  }

  public static String getUidJPEG2000ImageCompressionLosslessOnly_1_2_840_10008_1_2_4_90() {
    return imebraJNI.uidJPEG2000ImageCompressionLosslessOnly_1_2_840_10008_1_2_4_90_get();
  }

  public static String getUidJPEG2000ImageCompression_1_2_840_10008_1_2_4_91() {
    return imebraJNI.uidJPEG2000ImageCompression_1_2_840_10008_1_2_4_91_get();
  }

  public static String getUidJPEG2000Part2MulticomponentImageCompressionLosslessOnly_1_2_840_10008_1_2_4_92() {
    return imebraJNI.uidJPEG2000Part2MulticomponentImageCompressionLosslessOnly_1_2_840_10008_1_2_4_92_get();
  }

  public static String getUidJPEG2000Part2MulticomponentImageCompression_1_2_840_10008_1_2_4_93() {
    return imebraJNI.uidJPEG2000Part2MulticomponentImageCompression_1_2_840_10008_1_2_4_93_get();
  }

  public static String getUidJPIPReferenced_1_2_840_10008_1_2_4_94() {
    return imebraJNI.uidJPIPReferenced_1_2_840_10008_1_2_4_94_get();
  }

  public static String getUidJPIPReferencedDeflate_1_2_840_10008_1_2_4_95() {
    return imebraJNI.uidJPIPReferencedDeflate_1_2_840_10008_1_2_4_95_get();
  }

  public static String getUidMPEG2MainProfileMainLevel_1_2_840_10008_1_2_4_100() {
    return imebraJNI.uidMPEG2MainProfileMainLevel_1_2_840_10008_1_2_4_100_get();
  }

  public static String getUidMPEG2MainProfileHighLevel_1_2_840_10008_1_2_4_101() {
    return imebraJNI.uidMPEG2MainProfileHighLevel_1_2_840_10008_1_2_4_101_get();
  }

  public static String getUidMPEG4AVCH264HighProfileLevel41_1_2_840_10008_1_2_4_102() {
    return imebraJNI.uidMPEG4AVCH264HighProfileLevel41_1_2_840_10008_1_2_4_102_get();
  }

  public static String getUidMPEG4AVCH264BDcompatibleHighProfileLevel41_1_2_840_10008_1_2_4_103() {
    return imebraJNI.uidMPEG4AVCH264BDcompatibleHighProfileLevel41_1_2_840_10008_1_2_4_103_get();
  }

  public static String getUidMPEG4AVCH264HighProfileLevel42For2DVideo_1_2_840_10008_1_2_4_104() {
    return imebraJNI.uidMPEG4AVCH264HighProfileLevel42For2DVideo_1_2_840_10008_1_2_4_104_get();
  }

  public static String getUidMPEG4AVCH264HighProfileLevel42For3DVideo_1_2_840_10008_1_2_4_105() {
    return imebraJNI.uidMPEG4AVCH264HighProfileLevel42For3DVideo_1_2_840_10008_1_2_4_105_get();
  }

  public static String getUidMPEG4AVCH264StereoHighProfileLevel42_1_2_840_10008_1_2_4_106() {
    return imebraJNI.uidMPEG4AVCH264StereoHighProfileLevel42_1_2_840_10008_1_2_4_106_get();
  }

  public static String getUidHEVCH265MainProfileLevel51_1_2_840_10008_1_2_4_107() {
    return imebraJNI.uidHEVCH265MainProfileLevel51_1_2_840_10008_1_2_4_107_get();
  }

  public static String getUidHEVCH265Main10ProfileLevel51_1_2_840_10008_1_2_4_108() {
    return imebraJNI.uidHEVCH265Main10ProfileLevel51_1_2_840_10008_1_2_4_108_get();
  }

  public static String getUidRLELossless_1_2_840_10008_1_2_5() {
    return imebraJNI.uidRLELossless_1_2_840_10008_1_2_5_get();
  }

  public static String getUidRFC2557MIMEencapsulation_1_2_840_10008_1_2_6_1() {
    return imebraJNI.uidRFC2557MIMEencapsulation_1_2_840_10008_1_2_6_1_get();
  }

  public static String getUidXMLEncoding_1_2_840_10008_1_2_6_2() {
    return imebraJNI.uidXMLEncoding_1_2_840_10008_1_2_6_2_get();
  }

  public static String getUidMediaStorageDirectoryStorage_1_2_840_10008_1_3_10() {
    return imebraJNI.uidMediaStorageDirectoryStorage_1_2_840_10008_1_3_10_get();
  }

  public static String getUidTalairachBrainAtlasFrameofReference_1_2_840_10008_1_4_1_1() {
    return imebraJNI.uidTalairachBrainAtlasFrameofReference_1_2_840_10008_1_4_1_1_get();
  }

  public static String getUidSPM2T1FrameofReference_1_2_840_10008_1_4_1_2() {
    return imebraJNI.uidSPM2T1FrameofReference_1_2_840_10008_1_4_1_2_get();
  }

  public static String getUidSPM2T2FrameofReference_1_2_840_10008_1_4_1_3() {
    return imebraJNI.uidSPM2T2FrameofReference_1_2_840_10008_1_4_1_3_get();
  }

  public static String getUidSPM2PDFrameofReference_1_2_840_10008_1_4_1_4() {
    return imebraJNI.uidSPM2PDFrameofReference_1_2_840_10008_1_4_1_4_get();
  }

  public static String getUidSPM2EPIFrameofReference_1_2_840_10008_1_4_1_5() {
    return imebraJNI.uidSPM2EPIFrameofReference_1_2_840_10008_1_4_1_5_get();
  }

  public static String getUidSPM2FILT1FrameofReference_1_2_840_10008_1_4_1_6() {
    return imebraJNI.uidSPM2FILT1FrameofReference_1_2_840_10008_1_4_1_6_get();
  }

  public static String getUidSPM2PETFrameofReference_1_2_840_10008_1_4_1_7() {
    return imebraJNI.uidSPM2PETFrameofReference_1_2_840_10008_1_4_1_7_get();
  }

  public static String getUidSPM2TRANSMFrameofReference_1_2_840_10008_1_4_1_8() {
    return imebraJNI.uidSPM2TRANSMFrameofReference_1_2_840_10008_1_4_1_8_get();
  }

  public static String getUidSPM2SPECTFrameofReference_1_2_840_10008_1_4_1_9() {
    return imebraJNI.uidSPM2SPECTFrameofReference_1_2_840_10008_1_4_1_9_get();
  }

  public static String getUidSPM2GRAYFrameofReference_1_2_840_10008_1_4_1_10() {
    return imebraJNI.uidSPM2GRAYFrameofReference_1_2_840_10008_1_4_1_10_get();
  }

  public static String getUidSPM2WHITEFrameofReference_1_2_840_10008_1_4_1_11() {
    return imebraJNI.uidSPM2WHITEFrameofReference_1_2_840_10008_1_4_1_11_get();
  }

  public static String getUidSPM2CSFFrameofReference_1_2_840_10008_1_4_1_12() {
    return imebraJNI.uidSPM2CSFFrameofReference_1_2_840_10008_1_4_1_12_get();
  }

  public static String getUidSPM2BRAINMASKFrameofReference_1_2_840_10008_1_4_1_13() {
    return imebraJNI.uidSPM2BRAINMASKFrameofReference_1_2_840_10008_1_4_1_13_get();
  }

  public static String getUidSPM2AVG305T1FrameofReference_1_2_840_10008_1_4_1_14() {
    return imebraJNI.uidSPM2AVG305T1FrameofReference_1_2_840_10008_1_4_1_14_get();
  }

  public static String getUidSPM2AVG152T1FrameofReference_1_2_840_10008_1_4_1_15() {
    return imebraJNI.uidSPM2AVG152T1FrameofReference_1_2_840_10008_1_4_1_15_get();
  }

  public static String getUidSPM2AVG152T2FrameofReference_1_2_840_10008_1_4_1_16() {
    return imebraJNI.uidSPM2AVG152T2FrameofReference_1_2_840_10008_1_4_1_16_get();
  }

  public static String getUidSPM2AVG152PDFrameofReference_1_2_840_10008_1_4_1_17() {
    return imebraJNI.uidSPM2AVG152PDFrameofReference_1_2_840_10008_1_4_1_17_get();
  }

  public static String getUidSPM2SINGLESUBJT1FrameofReference_1_2_840_10008_1_4_1_18() {
    return imebraJNI.uidSPM2SINGLESUBJT1FrameofReference_1_2_840_10008_1_4_1_18_get();
  }

  public static String getUidICBM452T1FrameofReference_1_2_840_10008_1_4_2_1() {
    return imebraJNI.uidICBM452T1FrameofReference_1_2_840_10008_1_4_2_1_get();
  }

  public static String getUidICBMSingleSubjectMRIFrameofReference_1_2_840_10008_1_4_2_2() {
    return imebraJNI.uidICBMSingleSubjectMRIFrameofReference_1_2_840_10008_1_4_2_2_get();
  }

  public static String getUidHotIronColorPaletteSOPInstance_1_2_840_10008_1_5_1() {
    return imebraJNI.uidHotIronColorPaletteSOPInstance_1_2_840_10008_1_5_1_get();
  }

  public static String getUidPETColorPaletteSOPInstance_1_2_840_10008_1_5_2() {
    return imebraJNI.uidPETColorPaletteSOPInstance_1_2_840_10008_1_5_2_get();
  }

  public static String getUidHotMetalBlueColorPaletteSOPInstance_1_2_840_10008_1_5_3() {
    return imebraJNI.uidHotMetalBlueColorPaletteSOPInstance_1_2_840_10008_1_5_3_get();
  }

  public static String getUidPET20StepColorPaletteSOPInstance_1_2_840_10008_1_5_4() {
    return imebraJNI.uidPET20StepColorPaletteSOPInstance_1_2_840_10008_1_5_4_get();
  }

  public static String getUidSpringColorPaletteSOPInstance_1_2_840_10008_1_5_5() {
    return imebraJNI.uidSpringColorPaletteSOPInstance_1_2_840_10008_1_5_5_get();
  }

  public static String getUidSummerColorPaletteSOPInstance_1_2_840_10008_1_5_6() {
    return imebraJNI.uidSummerColorPaletteSOPInstance_1_2_840_10008_1_5_6_get();
  }

  public static String getUidFallColorPaletteSOPInstance_1_2_840_10008_1_5_7() {
    return imebraJNI.uidFallColorPaletteSOPInstance_1_2_840_10008_1_5_7_get();
  }

  public static String getUidWinterColorPaletteSOPInstance_1_2_840_10008_1_5_8() {
    return imebraJNI.uidWinterColorPaletteSOPInstance_1_2_840_10008_1_5_8_get();
  }

  public static String getUidBasicStudyContentNotificationSOPClass_1_2_840_10008_1_9() {
    return imebraJNI.uidBasicStudyContentNotificationSOPClass_1_2_840_10008_1_9_get();
  }

  public static String getUidPapyrus3ImplicitVRLittleEndian_1_2_840_10008_1_20() {
    return imebraJNI.uidPapyrus3ImplicitVRLittleEndian_1_2_840_10008_1_20_get();
  }

  public static String getUidStorageCommitmentPushModelSOPClass_1_2_840_10008_1_20_1() {
    return imebraJNI.uidStorageCommitmentPushModelSOPClass_1_2_840_10008_1_20_1_get();
  }

  public static String getUidStorageCommitmentPushModelSOPInstance_1_2_840_10008_1_20_1_1() {
    return imebraJNI.uidStorageCommitmentPushModelSOPInstance_1_2_840_10008_1_20_1_1_get();
  }

  public static String getUidStorageCommitmentPullModelSOPClass_1_2_840_10008_1_20_2() {
    return imebraJNI.uidStorageCommitmentPullModelSOPClass_1_2_840_10008_1_20_2_get();
  }

  public static String getUidStorageCommitmentPullModelSOPInstance_1_2_840_10008_1_20_2_1() {
    return imebraJNI.uidStorageCommitmentPullModelSOPInstance_1_2_840_10008_1_20_2_1_get();
  }

  public static String getUidProceduralEventLoggingSOPClass_1_2_840_10008_1_40() {
    return imebraJNI.uidProceduralEventLoggingSOPClass_1_2_840_10008_1_40_get();
  }

  public static String getUidProceduralEventLoggingSOPInstance_1_2_840_10008_1_40_1() {
    return imebraJNI.uidProceduralEventLoggingSOPInstance_1_2_840_10008_1_40_1_get();
  }

  public static String getUidSubstanceAdministrationLoggingSOPClass_1_2_840_10008_1_42() {
    return imebraJNI.uidSubstanceAdministrationLoggingSOPClass_1_2_840_10008_1_42_get();
  }

  public static String getUidSubstanceAdministrationLoggingSOPInstance_1_2_840_10008_1_42_1() {
    return imebraJNI.uidSubstanceAdministrationLoggingSOPInstance_1_2_840_10008_1_42_1_get();
  }

  public static String getUidDICOMUIDRegistry_1_2_840_10008_2_6_1() {
    return imebraJNI.uidDICOMUIDRegistry_1_2_840_10008_2_6_1_get();
  }

  public static String getUidDICOMControlledTerminology_1_2_840_10008_2_16_4() {
    return imebraJNI.uidDICOMControlledTerminology_1_2_840_10008_2_16_4_get();
  }

  public static String getUidAdultMouseAnatomyOntology_1_2_840_10008_2_16_5() {
    return imebraJNI.uidAdultMouseAnatomyOntology_1_2_840_10008_2_16_5_get();
  }

  public static String getUidUberonOntology_1_2_840_10008_2_16_6() {
    return imebraJNI.uidUberonOntology_1_2_840_10008_2_16_6_get();
  }

  public static String getUidIntegratedTaxonomicInformationSystemITISTaxonomicSerialNumberTSN_1_2_840_10008_2_16_7() {
    return imebraJNI.uidIntegratedTaxonomicInformationSystemITISTaxonomicSerialNumberTSN_1_2_840_10008_2_16_7_get();
  }

  public static String getUidMouseGenomeInitiativeMGI_1_2_840_10008_2_16_8() {
    return imebraJNI.uidMouseGenomeInitiativeMGI_1_2_840_10008_2_16_8_get();
  }

  public static String getUidPubChemCompoundCID_1_2_840_10008_2_16_9() {
    return imebraJNI.uidPubChemCompoundCID_1_2_840_10008_2_16_9_get();
  }

  public static String getUidDICOMApplicationContextName_1_2_840_10008_3_1_1_1() {
    return imebraJNI.uidDICOMApplicationContextName_1_2_840_10008_3_1_1_1_get();
  }

  public static String getUidDetachedPatientManagementSOPClass_1_2_840_10008_3_1_2_1_1() {
    return imebraJNI.uidDetachedPatientManagementSOPClass_1_2_840_10008_3_1_2_1_1_get();
  }

  public static String getUidDetachedPatientManagementMetaSOPClass_1_2_840_10008_3_1_2_1_4() {
    return imebraJNI.uidDetachedPatientManagementMetaSOPClass_1_2_840_10008_3_1_2_1_4_get();
  }

  public static String getUidDetachedVisitManagementSOPClass_1_2_840_10008_3_1_2_2_1() {
    return imebraJNI.uidDetachedVisitManagementSOPClass_1_2_840_10008_3_1_2_2_1_get();
  }

  public static String getUidDetachedStudyManagementSOPClass_1_2_840_10008_3_1_2_3_1() {
    return imebraJNI.uidDetachedStudyManagementSOPClass_1_2_840_10008_3_1_2_3_1_get();
  }

  public static String getUidStudyComponentManagementSOPClass_1_2_840_10008_3_1_2_3_2() {
    return imebraJNI.uidStudyComponentManagementSOPClass_1_2_840_10008_3_1_2_3_2_get();
  }

  public static String getUidModalityPerformedProcedureStepSOPClass_1_2_840_10008_3_1_2_3_3() {
    return imebraJNI.uidModalityPerformedProcedureStepSOPClass_1_2_840_10008_3_1_2_3_3_get();
  }

  public static String getUidModalityPerformedProcedureStepRetrieveSOPClass_1_2_840_10008_3_1_2_3_4() {
    return imebraJNI.uidModalityPerformedProcedureStepRetrieveSOPClass_1_2_840_10008_3_1_2_3_4_get();
  }

  public static String getUidModalityPerformedProcedureStepNotificationSOPClass_1_2_840_10008_3_1_2_3_5() {
    return imebraJNI.uidModalityPerformedProcedureStepNotificationSOPClass_1_2_840_10008_3_1_2_3_5_get();
  }

  public static String getUidDetachedResultsManagementSOPClass_1_2_840_10008_3_1_2_5_1() {
    return imebraJNI.uidDetachedResultsManagementSOPClass_1_2_840_10008_3_1_2_5_1_get();
  }

  public static String getUidDetachedResultsManagementMetaSOPClass_1_2_840_10008_3_1_2_5_4() {
    return imebraJNI.uidDetachedResultsManagementMetaSOPClass_1_2_840_10008_3_1_2_5_4_get();
  }

  public static String getUidDetachedStudyManagementMetaSOPClass_1_2_840_10008_3_1_2_5_5() {
    return imebraJNI.uidDetachedStudyManagementMetaSOPClass_1_2_840_10008_3_1_2_5_5_get();
  }

  public static String getUidDetachedInterpretationManagementSOPClass_1_2_840_10008_3_1_2_6_1() {
    return imebraJNI.uidDetachedInterpretationManagementSOPClass_1_2_840_10008_3_1_2_6_1_get();
  }

  public static String getUidStorageServiceClass_1_2_840_10008_4_2() {
    return imebraJNI.uidStorageServiceClass_1_2_840_10008_4_2_get();
  }

  public static String getUidBasicFilmSessionSOPClass_1_2_840_10008_5_1_1_1() {
    return imebraJNI.uidBasicFilmSessionSOPClass_1_2_840_10008_5_1_1_1_get();
  }

  public static String getUidBasicFilmBoxSOPClass_1_2_840_10008_5_1_1_2() {
    return imebraJNI.uidBasicFilmBoxSOPClass_1_2_840_10008_5_1_1_2_get();
  }

  public static String getUidBasicGrayscaleImageBoxSOPClass_1_2_840_10008_5_1_1_4() {
    return imebraJNI.uidBasicGrayscaleImageBoxSOPClass_1_2_840_10008_5_1_1_4_get();
  }

  public static String getUidBasicColorImageBoxSOPClass_1_2_840_10008_5_1_1_4_1() {
    return imebraJNI.uidBasicColorImageBoxSOPClass_1_2_840_10008_5_1_1_4_1_get();
  }

  public static String getUidReferencedImageBoxSOPClass_1_2_840_10008_5_1_1_4_2() {
    return imebraJNI.uidReferencedImageBoxSOPClass_1_2_840_10008_5_1_1_4_2_get();
  }

  public static String getUidBasicGrayscalePrintManagementMetaSOPClass_1_2_840_10008_5_1_1_9() {
    return imebraJNI.uidBasicGrayscalePrintManagementMetaSOPClass_1_2_840_10008_5_1_1_9_get();
  }

  public static String getUidReferencedGrayscalePrintManagementMetaSOPClass_1_2_840_10008_5_1_1_9_1() {
    return imebraJNI.uidReferencedGrayscalePrintManagementMetaSOPClass_1_2_840_10008_5_1_1_9_1_get();
  }

  public static String getUidPrintJobSOPClass_1_2_840_10008_5_1_1_14() {
    return imebraJNI.uidPrintJobSOPClass_1_2_840_10008_5_1_1_14_get();
  }

  public static String getUidBasicAnnotationBoxSOPClass_1_2_840_10008_5_1_1_15() {
    return imebraJNI.uidBasicAnnotationBoxSOPClass_1_2_840_10008_5_1_1_15_get();
  }

  public static String getUidPrinterSOPClass_1_2_840_10008_5_1_1_16() {
    return imebraJNI.uidPrinterSOPClass_1_2_840_10008_5_1_1_16_get();
  }

  public static String getUidPrinterConfigurationRetrievalSOPClass_1_2_840_10008_5_1_1_16_376() {
    return imebraJNI.uidPrinterConfigurationRetrievalSOPClass_1_2_840_10008_5_1_1_16_376_get();
  }

  public static String getUidPrinterSOPInstance_1_2_840_10008_5_1_1_17() {
    return imebraJNI.uidPrinterSOPInstance_1_2_840_10008_5_1_1_17_get();
  }

  public static String getUidPrinterConfigurationRetrievalSOPInstance_1_2_840_10008_5_1_1_17_376() {
    return imebraJNI.uidPrinterConfigurationRetrievalSOPInstance_1_2_840_10008_5_1_1_17_376_get();
  }

  public static String getUidBasicColorPrintManagementMetaSOPClass_1_2_840_10008_5_1_1_18() {
    return imebraJNI.uidBasicColorPrintManagementMetaSOPClass_1_2_840_10008_5_1_1_18_get();
  }

  public static String getUidReferencedColorPrintManagementMetaSOPClass_1_2_840_10008_5_1_1_18_1() {
    return imebraJNI.uidReferencedColorPrintManagementMetaSOPClass_1_2_840_10008_5_1_1_18_1_get();
  }

  public static String getUidVOILUTBoxSOPClass_1_2_840_10008_5_1_1_22() {
    return imebraJNI.uidVOILUTBoxSOPClass_1_2_840_10008_5_1_1_22_get();
  }

  public static String getUidPresentationLUTSOPClass_1_2_840_10008_5_1_1_23() {
    return imebraJNI.uidPresentationLUTSOPClass_1_2_840_10008_5_1_1_23_get();
  }

  public static String getUidImageOverlayBoxSOPClass_1_2_840_10008_5_1_1_24() {
    return imebraJNI.uidImageOverlayBoxSOPClass_1_2_840_10008_5_1_1_24_get();
  }

  public static String getUidBasicPrintImageOverlayBoxSOPClass_1_2_840_10008_5_1_1_24_1() {
    return imebraJNI.uidBasicPrintImageOverlayBoxSOPClass_1_2_840_10008_5_1_1_24_1_get();
  }

  public static String getUidPrintQueueSOPInstance_1_2_840_10008_5_1_1_25() {
    return imebraJNI.uidPrintQueueSOPInstance_1_2_840_10008_5_1_1_25_get();
  }

  public static String getUidPrintQueueManagementSOPClass_1_2_840_10008_5_1_1_26() {
    return imebraJNI.uidPrintQueueManagementSOPClass_1_2_840_10008_5_1_1_26_get();
  }

  public static String getUidStoredPrintStorageSOPClass_1_2_840_10008_5_1_1_27() {
    return imebraJNI.uidStoredPrintStorageSOPClass_1_2_840_10008_5_1_1_27_get();
  }

  public static String getUidHardcopyGrayscaleImageStorageSOPClass_1_2_840_10008_5_1_1_29() {
    return imebraJNI.uidHardcopyGrayscaleImageStorageSOPClass_1_2_840_10008_5_1_1_29_get();
  }

  public static String getUidHardcopyColorImageStorageSOPClass_1_2_840_10008_5_1_1_30() {
    return imebraJNI.uidHardcopyColorImageStorageSOPClass_1_2_840_10008_5_1_1_30_get();
  }

  public static String getUidPullPrintRequestSOPClass_1_2_840_10008_5_1_1_31() {
    return imebraJNI.uidPullPrintRequestSOPClass_1_2_840_10008_5_1_1_31_get();
  }

  public static String getUidPullStoredPrintManagementMetaSOPClass_1_2_840_10008_5_1_1_32() {
    return imebraJNI.uidPullStoredPrintManagementMetaSOPClass_1_2_840_10008_5_1_1_32_get();
  }

  public static String getUidMediaCreationManagementSOPClassUID_1_2_840_10008_5_1_1_33() {
    return imebraJNI.uidMediaCreationManagementSOPClassUID_1_2_840_10008_5_1_1_33_get();
  }

  public static String getUidDisplaySystemSOPClass_1_2_840_10008_5_1_1_40() {
    return imebraJNI.uidDisplaySystemSOPClass_1_2_840_10008_5_1_1_40_get();
  }

  public static String getUidDisplaySystemSOPInstance_1_2_840_10008_5_1_1_40_1() {
    return imebraJNI.uidDisplaySystemSOPInstance_1_2_840_10008_5_1_1_40_1_get();
  }

  public static String getUidComputedRadiographyImageStorage_1_2_840_10008_5_1_4_1_1_1() {
    return imebraJNI.uidComputedRadiographyImageStorage_1_2_840_10008_5_1_4_1_1_1_get();
  }

  public static String getUidDigitalXRayImageStorageForPresentation_1_2_840_10008_5_1_4_1_1_1_1() {
    return imebraJNI.uidDigitalXRayImageStorageForPresentation_1_2_840_10008_5_1_4_1_1_1_1_get();
  }

  public static String getUidDigitalXRayImageStorageForProcessing_1_2_840_10008_5_1_4_1_1_1_1_1() {
    return imebraJNI.uidDigitalXRayImageStorageForProcessing_1_2_840_10008_5_1_4_1_1_1_1_1_get();
  }

  public static String getUidDigitalMammographyXRayImageStorageForPresentation_1_2_840_10008_5_1_4_1_1_1_2() {
    return imebraJNI.uidDigitalMammographyXRayImageStorageForPresentation_1_2_840_10008_5_1_4_1_1_1_2_get();
  }

  public static String getUidDigitalMammographyXRayImageStorageForProcessing_1_2_840_10008_5_1_4_1_1_1_2_1() {
    return imebraJNI.uidDigitalMammographyXRayImageStorageForProcessing_1_2_840_10008_5_1_4_1_1_1_2_1_get();
  }

  public static String getUidDigitalIntraOralXRayImageStorageForPresentation_1_2_840_10008_5_1_4_1_1_1_3() {
    return imebraJNI.uidDigitalIntraOralXRayImageStorageForPresentation_1_2_840_10008_5_1_4_1_1_1_3_get();
  }

  public static String getUidDigitalIntraOralXRayImageStorageForProcessing_1_2_840_10008_5_1_4_1_1_1_3_1() {
    return imebraJNI.uidDigitalIntraOralXRayImageStorageForProcessing_1_2_840_10008_5_1_4_1_1_1_3_1_get();
  }

  public static String getUidCTImageStorage_1_2_840_10008_5_1_4_1_1_2() {
    return imebraJNI.uidCTImageStorage_1_2_840_10008_5_1_4_1_1_2_get();
  }

  public static String getUidEnhancedCTImageStorage_1_2_840_10008_5_1_4_1_1_2_1() {
    return imebraJNI.uidEnhancedCTImageStorage_1_2_840_10008_5_1_4_1_1_2_1_get();
  }

  public static String getUidLegacyConvertedEnhancedCTImageStorage_1_2_840_10008_5_1_4_1_1_2_2() {
    return imebraJNI.uidLegacyConvertedEnhancedCTImageStorage_1_2_840_10008_5_1_4_1_1_2_2_get();
  }

  public static String getUidUltrasoundMultiframeImageStorageRetired_1_2_840_10008_5_1_4_1_1_3() {
    return imebraJNI.uidUltrasoundMultiframeImageStorageRetired_1_2_840_10008_5_1_4_1_1_3_get();
  }

  public static String getUidUltrasoundMultiframeImageStorage_1_2_840_10008_5_1_4_1_1_3_1() {
    return imebraJNI.uidUltrasoundMultiframeImageStorage_1_2_840_10008_5_1_4_1_1_3_1_get();
  }

  public static String getUidMRImageStorage_1_2_840_10008_5_1_4_1_1_4() {
    return imebraJNI.uidMRImageStorage_1_2_840_10008_5_1_4_1_1_4_get();
  }

  public static String getUidEnhancedMRImageStorage_1_2_840_10008_5_1_4_1_1_4_1() {
    return imebraJNI.uidEnhancedMRImageStorage_1_2_840_10008_5_1_4_1_1_4_1_get();
  }

  public static String getUidMRSpectroscopyStorage_1_2_840_10008_5_1_4_1_1_4_2() {
    return imebraJNI.uidMRSpectroscopyStorage_1_2_840_10008_5_1_4_1_1_4_2_get();
  }

  public static String getUidEnhancedMRColorImageStorage_1_2_840_10008_5_1_4_1_1_4_3() {
    return imebraJNI.uidEnhancedMRColorImageStorage_1_2_840_10008_5_1_4_1_1_4_3_get();
  }

  public static String getUidLegacyConvertedEnhancedMRImageStorage_1_2_840_10008_5_1_4_1_1_4_4() {
    return imebraJNI.uidLegacyConvertedEnhancedMRImageStorage_1_2_840_10008_5_1_4_1_1_4_4_get();
  }

  public static String getUidUltrasoundImageStorageRetired_1_2_840_10008_5_1_4_1_1_6() {
    return imebraJNI.uidUltrasoundImageStorageRetired_1_2_840_10008_5_1_4_1_1_6_get();
  }

  public static String getUidUltrasoundImageStorage_1_2_840_10008_5_1_4_1_1_6_1() {
    return imebraJNI.uidUltrasoundImageStorage_1_2_840_10008_5_1_4_1_1_6_1_get();
  }

  public static String getUidEnhancedUSVolumeStorage_1_2_840_10008_5_1_4_1_1_6_2() {
    return imebraJNI.uidEnhancedUSVolumeStorage_1_2_840_10008_5_1_4_1_1_6_2_get();
  }

  public static String getUidSecondaryCaptureImageStorage_1_2_840_10008_5_1_4_1_1_7() {
    return imebraJNI.uidSecondaryCaptureImageStorage_1_2_840_10008_5_1_4_1_1_7_get();
  }

  public static String getUidMultiframeSingleBitSecondaryCaptureImageStorage_1_2_840_10008_5_1_4_1_1_7_1() {
    return imebraJNI.uidMultiframeSingleBitSecondaryCaptureImageStorage_1_2_840_10008_5_1_4_1_1_7_1_get();
  }

  public static String getUidMultiframeGrayscaleByteSecondaryCaptureImageStorage_1_2_840_10008_5_1_4_1_1_7_2() {
    return imebraJNI.uidMultiframeGrayscaleByteSecondaryCaptureImageStorage_1_2_840_10008_5_1_4_1_1_7_2_get();
  }

  public static String getUidMultiframeGrayscaleWordSecondaryCaptureImageStorage_1_2_840_10008_5_1_4_1_1_7_3() {
    return imebraJNI.uidMultiframeGrayscaleWordSecondaryCaptureImageStorage_1_2_840_10008_5_1_4_1_1_7_3_get();
  }

  public static String getUidMultiframeTrueColorSecondaryCaptureImageStorage_1_2_840_10008_5_1_4_1_1_7_4() {
    return imebraJNI.uidMultiframeTrueColorSecondaryCaptureImageStorage_1_2_840_10008_5_1_4_1_1_7_4_get();
  }

  public static String getUidStandaloneOverlayStorage_1_2_840_10008_5_1_4_1_1_8() {
    return imebraJNI.uidStandaloneOverlayStorage_1_2_840_10008_5_1_4_1_1_8_get();
  }

  public static String getUidStandaloneCurveStorage_1_2_840_10008_5_1_4_1_1_9() {
    return imebraJNI.uidStandaloneCurveStorage_1_2_840_10008_5_1_4_1_1_9_get();
  }

  public static String getUidWaveformStorageTrial_1_2_840_10008_5_1_4_1_1_9_1() {
    return imebraJNI.uidWaveformStorageTrial_1_2_840_10008_5_1_4_1_1_9_1_get();
  }

  public static String getUid12leadECGWaveformStorage_1_2_840_10008_5_1_4_1_1_9_1_1() {
    return imebraJNI.uid12leadECGWaveformStorage_1_2_840_10008_5_1_4_1_1_9_1_1_get();
  }

  public static String getUidGeneralECGWaveformStorage_1_2_840_10008_5_1_4_1_1_9_1_2() {
    return imebraJNI.uidGeneralECGWaveformStorage_1_2_840_10008_5_1_4_1_1_9_1_2_get();
  }

  public static String getUidAmbulatoryECGWaveformStorage_1_2_840_10008_5_1_4_1_1_9_1_3() {
    return imebraJNI.uidAmbulatoryECGWaveformStorage_1_2_840_10008_5_1_4_1_1_9_1_3_get();
  }

  public static String getUidHemodynamicWaveformStorage_1_2_840_10008_5_1_4_1_1_9_2_1() {
    return imebraJNI.uidHemodynamicWaveformStorage_1_2_840_10008_5_1_4_1_1_9_2_1_get();
  }

  public static String getUidCardiacElectrophysiologyWaveformStorage_1_2_840_10008_5_1_4_1_1_9_3_1() {
    return imebraJNI.uidCardiacElectrophysiologyWaveformStorage_1_2_840_10008_5_1_4_1_1_9_3_1_get();
  }

  public static String getUidBasicVoiceAudioWaveformStorage_1_2_840_10008_5_1_4_1_1_9_4_1() {
    return imebraJNI.uidBasicVoiceAudioWaveformStorage_1_2_840_10008_5_1_4_1_1_9_4_1_get();
  }

  public static String getUidGeneralAudioWaveformStorage_1_2_840_10008_5_1_4_1_1_9_4_2() {
    return imebraJNI.uidGeneralAudioWaveformStorage_1_2_840_10008_5_1_4_1_1_9_4_2_get();
  }

  public static String getUidArterialPulseWaveformStorage_1_2_840_10008_5_1_4_1_1_9_5_1() {
    return imebraJNI.uidArterialPulseWaveformStorage_1_2_840_10008_5_1_4_1_1_9_5_1_get();
  }

  public static String getUidRespiratoryWaveformStorage_1_2_840_10008_5_1_4_1_1_9_6_1() {
    return imebraJNI.uidRespiratoryWaveformStorage_1_2_840_10008_5_1_4_1_1_9_6_1_get();
  }

  public static String getUidStandaloneModalityLUTStorage_1_2_840_10008_5_1_4_1_1_10() {
    return imebraJNI.uidStandaloneModalityLUTStorage_1_2_840_10008_5_1_4_1_1_10_get();
  }

  public static String getUidStandaloneVOILUTStorage_1_2_840_10008_5_1_4_1_1_11() {
    return imebraJNI.uidStandaloneVOILUTStorage_1_2_840_10008_5_1_4_1_1_11_get();
  }

  public static String getUidGrayscaleSoftcopyPresentationStateStorage_1_2_840_10008_5_1_4_1_1_11_1() {
    return imebraJNI.uidGrayscaleSoftcopyPresentationStateStorage_1_2_840_10008_5_1_4_1_1_11_1_get();
  }

  public static String getUidColorSoftcopyPresentationStateStorage_1_2_840_10008_5_1_4_1_1_11_2() {
    return imebraJNI.uidColorSoftcopyPresentationStateStorage_1_2_840_10008_5_1_4_1_1_11_2_get();
  }

  public static String getUidPseudoColorSoftcopyPresentationStateStorage_1_2_840_10008_5_1_4_1_1_11_3() {
    return imebraJNI.uidPseudoColorSoftcopyPresentationStateStorage_1_2_840_10008_5_1_4_1_1_11_3_get();
  }

  public static String getUidBlendingSoftcopyPresentationStateStorage_1_2_840_10008_5_1_4_1_1_11_4() {
    return imebraJNI.uidBlendingSoftcopyPresentationStateStorage_1_2_840_10008_5_1_4_1_1_11_4_get();
  }

  public static String getUidXAXRFGrayscaleSoftcopyPresentationStateStorage_1_2_840_10008_5_1_4_1_1_11_5() {
    return imebraJNI.uidXAXRFGrayscaleSoftcopyPresentationStateStorage_1_2_840_10008_5_1_4_1_1_11_5_get();
  }

  public static String getUidGrayscalePlanarMPRVolumetricPresentationStateStorage_1_2_840_10008_5_1_4_1_1_11_6() {
    return imebraJNI.uidGrayscalePlanarMPRVolumetricPresentationStateStorage_1_2_840_10008_5_1_4_1_1_11_6_get();
  }

  public static String getUidCompositingPlanarMPRVolumetricPresentationStateStorage_1_2_840_10008_5_1_4_1_1_11_7() {
    return imebraJNI.uidCompositingPlanarMPRVolumetricPresentationStateStorage_1_2_840_10008_5_1_4_1_1_11_7_get();
  }

  public static String getUidAdvancedBlendingPresentationStateStorage_1_2_840_10008_5_1_4_1_1_11_8() {
    return imebraJNI.uidAdvancedBlendingPresentationStateStorage_1_2_840_10008_5_1_4_1_1_11_8_get();
  }

  public static String getUidVolumeRenderingVolumetricPresentationStateStorage_1_2_840_10008_5_1_4_1_1_11_9() {
    return imebraJNI.uidVolumeRenderingVolumetricPresentationStateStorage_1_2_840_10008_5_1_4_1_1_11_9_get();
  }

  public static String getUidSegmentedVolumeRenderingVolumetricPresentationStateStorage_1_2_840_10008_5_1_4_1_1_11_10() {
    return imebraJNI.uidSegmentedVolumeRenderingVolumetricPresentationStateStorage_1_2_840_10008_5_1_4_1_1_11_10_get();
  }

  public static String getUidMultipleVolumeRenderingVolumetricPresentationStateStorage_1_2_840_10008_5_1_4_1_1_11_11() {
    return imebraJNI.uidMultipleVolumeRenderingVolumetricPresentationStateStorage_1_2_840_10008_5_1_4_1_1_11_11_get();
  }

  public static String getUidXRayAngiographicImageStorage_1_2_840_10008_5_1_4_1_1_12_1() {
    return imebraJNI.uidXRayAngiographicImageStorage_1_2_840_10008_5_1_4_1_1_12_1_get();
  }

  public static String getUidEnhancedXAImageStorage_1_2_840_10008_5_1_4_1_1_12_1_1() {
    return imebraJNI.uidEnhancedXAImageStorage_1_2_840_10008_5_1_4_1_1_12_1_1_get();
  }

  public static String getUidXRayRadiofluoroscopicImageStorage_1_2_840_10008_5_1_4_1_1_12_2() {
    return imebraJNI.uidXRayRadiofluoroscopicImageStorage_1_2_840_10008_5_1_4_1_1_12_2_get();
  }

  public static String getUidEnhancedXRFImageStorage_1_2_840_10008_5_1_4_1_1_12_2_1() {
    return imebraJNI.uidEnhancedXRFImageStorage_1_2_840_10008_5_1_4_1_1_12_2_1_get();
  }

  public static String getUidXRayAngiographicBiPlaneImageStorage_1_2_840_10008_5_1_4_1_1_12_3() {
    return imebraJNI.uidXRayAngiographicBiPlaneImageStorage_1_2_840_10008_5_1_4_1_1_12_3_get();
  }

  public static String getUidXRay3DAngiographicImageStorage_1_2_840_10008_5_1_4_1_1_13_1_1() {
    return imebraJNI.uidXRay3DAngiographicImageStorage_1_2_840_10008_5_1_4_1_1_13_1_1_get();
  }

  public static String getUidXRay3DCraniofacialImageStorage_1_2_840_10008_5_1_4_1_1_13_1_2() {
    return imebraJNI.uidXRay3DCraniofacialImageStorage_1_2_840_10008_5_1_4_1_1_13_1_2_get();
  }

  public static String getUidBreastTomosynthesisImageStorage_1_2_840_10008_5_1_4_1_1_13_1_3() {
    return imebraJNI.uidBreastTomosynthesisImageStorage_1_2_840_10008_5_1_4_1_1_13_1_3_get();
  }

  public static String getUidBreastProjectionXRayImageStorageForPresentation_1_2_840_10008_5_1_4_1_1_13_1_4() {
    return imebraJNI.uidBreastProjectionXRayImageStorageForPresentation_1_2_840_10008_5_1_4_1_1_13_1_4_get();
  }

  public static String getUidBreastProjectionXRayImageStorageForProcessing_1_2_840_10008_5_1_4_1_1_13_1_5() {
    return imebraJNI.uidBreastProjectionXRayImageStorageForProcessing_1_2_840_10008_5_1_4_1_1_13_1_5_get();
  }

  public static String getUidIntravascularOpticalCoherenceTomographyImageStorageForPresentation_1_2_840_10008_5_1_4_1_1_14_1() {
    return imebraJNI.uidIntravascularOpticalCoherenceTomographyImageStorageForPresentation_1_2_840_10008_5_1_4_1_1_14_1_get();
  }

  public static String getUidIntravascularOpticalCoherenceTomographyImageStorageForProcessing_1_2_840_10008_5_1_4_1_1_14_2() {
    return imebraJNI.uidIntravascularOpticalCoherenceTomographyImageStorageForProcessing_1_2_840_10008_5_1_4_1_1_14_2_get();
  }

  public static String getUidNuclearMedicineImageStorageRetired_1_2_840_10008_5_1_4_1_1_5() {
    return imebraJNI.uidNuclearMedicineImageStorageRetired_1_2_840_10008_5_1_4_1_1_5_get();
  }

  public static String getUidNuclearMedicineImageStorage_1_2_840_10008_5_1_4_1_1_20() {
    return imebraJNI.uidNuclearMedicineImageStorage_1_2_840_10008_5_1_4_1_1_20_get();
  }

  public static String getUidParametricMapStorage_1_2_840_10008_5_1_4_1_1_30() {
    return imebraJNI.uidParametricMapStorage_1_2_840_10008_5_1_4_1_1_30_get();
  }

  public static String getUidRawDataStorage_1_2_840_10008_5_1_4_1_1_66() {
    return imebraJNI.uidRawDataStorage_1_2_840_10008_5_1_4_1_1_66_get();
  }

  public static String getUidSpatialRegistrationStorage_1_2_840_10008_5_1_4_1_1_66_1() {
    return imebraJNI.uidSpatialRegistrationStorage_1_2_840_10008_5_1_4_1_1_66_1_get();
  }

  public static String getUidSpatialFiducialsStorage_1_2_840_10008_5_1_4_1_1_66_2() {
    return imebraJNI.uidSpatialFiducialsStorage_1_2_840_10008_5_1_4_1_1_66_2_get();
  }

  public static String getUidDeformableSpatialRegistrationStorage_1_2_840_10008_5_1_4_1_1_66_3() {
    return imebraJNI.uidDeformableSpatialRegistrationStorage_1_2_840_10008_5_1_4_1_1_66_3_get();
  }

  public static String getUidSegmentationStorage_1_2_840_10008_5_1_4_1_1_66_4() {
    return imebraJNI.uidSegmentationStorage_1_2_840_10008_5_1_4_1_1_66_4_get();
  }

  public static String getUidSurfaceSegmentationStorage_1_2_840_10008_5_1_4_1_1_66_5() {
    return imebraJNI.uidSurfaceSegmentationStorage_1_2_840_10008_5_1_4_1_1_66_5_get();
  }

  public static String getUidTractographyResultsStorage_1_2_840_10008_5_1_4_1_1_66_6() {
    return imebraJNI.uidTractographyResultsStorage_1_2_840_10008_5_1_4_1_1_66_6_get();
  }

  public static String getUidRealWorldValueMappingStorage_1_2_840_10008_5_1_4_1_1_67() {
    return imebraJNI.uidRealWorldValueMappingStorage_1_2_840_10008_5_1_4_1_1_67_get();
  }

  public static String getUidSurfaceScanMeshStorage_1_2_840_10008_5_1_4_1_1_68_1() {
    return imebraJNI.uidSurfaceScanMeshStorage_1_2_840_10008_5_1_4_1_1_68_1_get();
  }

  public static String getUidSurfaceScanPointCloudStorage_1_2_840_10008_5_1_4_1_1_68_2() {
    return imebraJNI.uidSurfaceScanPointCloudStorage_1_2_840_10008_5_1_4_1_1_68_2_get();
  }

  public static String getUidVLImageStorageTrial_1_2_840_10008_5_1_4_1_1_77_1() {
    return imebraJNI.uidVLImageStorageTrial_1_2_840_10008_5_1_4_1_1_77_1_get();
  }

  public static String getUidVLMultiframeImageStorageTrial_1_2_840_10008_5_1_4_1_1_77_2() {
    return imebraJNI.uidVLMultiframeImageStorageTrial_1_2_840_10008_5_1_4_1_1_77_2_get();
  }

  public static String getUidVLEndoscopicImageStorage_1_2_840_10008_5_1_4_1_1_77_1_1() {
    return imebraJNI.uidVLEndoscopicImageStorage_1_2_840_10008_5_1_4_1_1_77_1_1_get();
  }

  public static String getUidVideoEndoscopicImageStorage_1_2_840_10008_5_1_4_1_1_77_1_1_1() {
    return imebraJNI.uidVideoEndoscopicImageStorage_1_2_840_10008_5_1_4_1_1_77_1_1_1_get();
  }

  public static String getUidVLMicroscopicImageStorage_1_2_840_10008_5_1_4_1_1_77_1_2() {
    return imebraJNI.uidVLMicroscopicImageStorage_1_2_840_10008_5_1_4_1_1_77_1_2_get();
  }

  public static String getUidVideoMicroscopicImageStorage_1_2_840_10008_5_1_4_1_1_77_1_2_1() {
    return imebraJNI.uidVideoMicroscopicImageStorage_1_2_840_10008_5_1_4_1_1_77_1_2_1_get();
  }

  public static String getUidVLSlideCoordinatesMicroscopicImageStorage_1_2_840_10008_5_1_4_1_1_77_1_3() {
    return imebraJNI.uidVLSlideCoordinatesMicroscopicImageStorage_1_2_840_10008_5_1_4_1_1_77_1_3_get();
  }

  public static String getUidVLPhotographicImageStorage_1_2_840_10008_5_1_4_1_1_77_1_4() {
    return imebraJNI.uidVLPhotographicImageStorage_1_2_840_10008_5_1_4_1_1_77_1_4_get();
  }

  public static String getUidVideoPhotographicImageStorage_1_2_840_10008_5_1_4_1_1_77_1_4_1() {
    return imebraJNI.uidVideoPhotographicImageStorage_1_2_840_10008_5_1_4_1_1_77_1_4_1_get();
  }

  public static String getUidOphthalmicPhotography8BitImageStorage_1_2_840_10008_5_1_4_1_1_77_1_5_1() {
    return imebraJNI.uidOphthalmicPhotography8BitImageStorage_1_2_840_10008_5_1_4_1_1_77_1_5_1_get();
  }

  public static String getUidOphthalmicPhotography16BitImageStorage_1_2_840_10008_5_1_4_1_1_77_1_5_2() {
    return imebraJNI.uidOphthalmicPhotography16BitImageStorage_1_2_840_10008_5_1_4_1_1_77_1_5_2_get();
  }

  public static String getUidStereometricRelationshipStorage_1_2_840_10008_5_1_4_1_1_77_1_5_3() {
    return imebraJNI.uidStereometricRelationshipStorage_1_2_840_10008_5_1_4_1_1_77_1_5_3_get();
  }

  public static String getUidOphthalmicTomographyImageStorage_1_2_840_10008_5_1_4_1_1_77_1_5_4() {
    return imebraJNI.uidOphthalmicTomographyImageStorage_1_2_840_10008_5_1_4_1_1_77_1_5_4_get();
  }

  public static String getUidWideFieldOphthalmicPhotographyStereographicProjectionImageStorage_1_2_840_10008_5_1_4_1_1_77_1_5_5() {
    return imebraJNI.uidWideFieldOphthalmicPhotographyStereographicProjectionImageStorage_1_2_840_10008_5_1_4_1_1_77_1_5_5_get();
  }

  public static String getUidWideFieldOphthalmicPhotography3DCoordinatesImageStorage_1_2_840_10008_5_1_4_1_1_77_1_5_6() {
    return imebraJNI.uidWideFieldOphthalmicPhotography3DCoordinatesImageStorage_1_2_840_10008_5_1_4_1_1_77_1_5_6_get();
  }

  public static String getUidOphthalmicOpticalCoherenceTomographyEnFaceImageStorage_1_2_840_10008_5_1_4_1_1_77_1_5_7() {
    return imebraJNI.uidOphthalmicOpticalCoherenceTomographyEnFaceImageStorage_1_2_840_10008_5_1_4_1_1_77_1_5_7_get();
  }

  public static String getUidOphthalmicOpticalCoherenceTomographyBscanVolumeAnalysisStorage_1_2_840_10008_5_1_4_1_1_77_1_5_8() {
    return imebraJNI.uidOphthalmicOpticalCoherenceTomographyBscanVolumeAnalysisStorage_1_2_840_10008_5_1_4_1_1_77_1_5_8_get();
  }

  public static String getUidVLWholeSlideMicroscopyImageStorage_1_2_840_10008_5_1_4_1_1_77_1_6() {
    return imebraJNI.uidVLWholeSlideMicroscopyImageStorage_1_2_840_10008_5_1_4_1_1_77_1_6_get();
  }

  public static String getUidLensometryMeasurementsStorage_1_2_840_10008_5_1_4_1_1_78_1() {
    return imebraJNI.uidLensometryMeasurementsStorage_1_2_840_10008_5_1_4_1_1_78_1_get();
  }

  public static String getUidAutorefractionMeasurementsStorage_1_2_840_10008_5_1_4_1_1_78_2() {
    return imebraJNI.uidAutorefractionMeasurementsStorage_1_2_840_10008_5_1_4_1_1_78_2_get();
  }

  public static String getUidKeratometryMeasurementsStorage_1_2_840_10008_5_1_4_1_1_78_3() {
    return imebraJNI.uidKeratometryMeasurementsStorage_1_2_840_10008_5_1_4_1_1_78_3_get();
  }

  public static String getUidSubjectiveRefractionMeasurementsStorage_1_2_840_10008_5_1_4_1_1_78_4() {
    return imebraJNI.uidSubjectiveRefractionMeasurementsStorage_1_2_840_10008_5_1_4_1_1_78_4_get();
  }

  public static String getUidVisualAcuityMeasurementsStorage_1_2_840_10008_5_1_4_1_1_78_5() {
    return imebraJNI.uidVisualAcuityMeasurementsStorage_1_2_840_10008_5_1_4_1_1_78_5_get();
  }

  public static String getUidSpectaclePrescriptionReportStorage_1_2_840_10008_5_1_4_1_1_78_6() {
    return imebraJNI.uidSpectaclePrescriptionReportStorage_1_2_840_10008_5_1_4_1_1_78_6_get();
  }

  public static String getUidOphthalmicAxialMeasurementsStorage_1_2_840_10008_5_1_4_1_1_78_7() {
    return imebraJNI.uidOphthalmicAxialMeasurementsStorage_1_2_840_10008_5_1_4_1_1_78_7_get();
  }

  public static String getUidIntraocularLensCalculationsStorage_1_2_840_10008_5_1_4_1_1_78_8() {
    return imebraJNI.uidIntraocularLensCalculationsStorage_1_2_840_10008_5_1_4_1_1_78_8_get();
  }

  public static String getUidMacularGridThicknessandVolumeReportStorage_1_2_840_10008_5_1_4_1_1_79_1() {
    return imebraJNI.uidMacularGridThicknessandVolumeReportStorage_1_2_840_10008_5_1_4_1_1_79_1_get();
  }

  public static String getUidOphthalmicVisualFieldStaticPerimetryMeasurementsStorage_1_2_840_10008_5_1_4_1_1_80_1() {
    return imebraJNI.uidOphthalmicVisualFieldStaticPerimetryMeasurementsStorage_1_2_840_10008_5_1_4_1_1_80_1_get();
  }

  public static String getUidOphthalmicThicknessMapStorage_1_2_840_10008_5_1_4_1_1_81_1() {
    return imebraJNI.uidOphthalmicThicknessMapStorage_1_2_840_10008_5_1_4_1_1_81_1_get();
  }

  public static String getUidCornealTopographyMapStorage_1_2_840_10008_5_1_4_1_1_82_1() {
    return imebraJNI.uidCornealTopographyMapStorage_1_2_840_10008_5_1_4_1_1_82_1_get();
  }

  public static String getUidTextSRStorageTrial_1_2_840_10008_5_1_4_1_1_88_1() {
    return imebraJNI.uidTextSRStorageTrial_1_2_840_10008_5_1_4_1_1_88_1_get();
  }

  public static String getUidAudioSRStorageTrial_1_2_840_10008_5_1_4_1_1_88_2() {
    return imebraJNI.uidAudioSRStorageTrial_1_2_840_10008_5_1_4_1_1_88_2_get();
  }

  public static String getUidDetailSRStorageTrial_1_2_840_10008_5_1_4_1_1_88_3() {
    return imebraJNI.uidDetailSRStorageTrial_1_2_840_10008_5_1_4_1_1_88_3_get();
  }

  public static String getUidComprehensiveSRStorageTrial_1_2_840_10008_5_1_4_1_1_88_4() {
    return imebraJNI.uidComprehensiveSRStorageTrial_1_2_840_10008_5_1_4_1_1_88_4_get();
  }

  public static String getUidBasicTextSRStorage_1_2_840_10008_5_1_4_1_1_88_11() {
    return imebraJNI.uidBasicTextSRStorage_1_2_840_10008_5_1_4_1_1_88_11_get();
  }

  public static String getUidEnhancedSRStorage_1_2_840_10008_5_1_4_1_1_88_22() {
    return imebraJNI.uidEnhancedSRStorage_1_2_840_10008_5_1_4_1_1_88_22_get();
  }

  public static String getUidComprehensiveSRStorage_1_2_840_10008_5_1_4_1_1_88_33() {
    return imebraJNI.uidComprehensiveSRStorage_1_2_840_10008_5_1_4_1_1_88_33_get();
  }

  public static String getUidComprehensive3DSRStorage_1_2_840_10008_5_1_4_1_1_88_34() {
    return imebraJNI.uidComprehensive3DSRStorage_1_2_840_10008_5_1_4_1_1_88_34_get();
  }

  public static String getUidExtensibleSRStorage_1_2_840_10008_5_1_4_1_1_88_35() {
    return imebraJNI.uidExtensibleSRStorage_1_2_840_10008_5_1_4_1_1_88_35_get();
  }

  public static String getUidProcedureLogStorage_1_2_840_10008_5_1_4_1_1_88_40() {
    return imebraJNI.uidProcedureLogStorage_1_2_840_10008_5_1_4_1_1_88_40_get();
  }

  public static String getUidMammographyCADSRStorage_1_2_840_10008_5_1_4_1_1_88_50() {
    return imebraJNI.uidMammographyCADSRStorage_1_2_840_10008_5_1_4_1_1_88_50_get();
  }

  public static String getUidKeyObjectSelectionDocumentStorage_1_2_840_10008_5_1_4_1_1_88_59() {
    return imebraJNI.uidKeyObjectSelectionDocumentStorage_1_2_840_10008_5_1_4_1_1_88_59_get();
  }

  public static String getUidChestCADSRStorage_1_2_840_10008_5_1_4_1_1_88_65() {
    return imebraJNI.uidChestCADSRStorage_1_2_840_10008_5_1_4_1_1_88_65_get();
  }

  public static String getUidXRayRadiationDoseSRStorage_1_2_840_10008_5_1_4_1_1_88_67() {
    return imebraJNI.uidXRayRadiationDoseSRStorage_1_2_840_10008_5_1_4_1_1_88_67_get();
  }

  public static String getUidRadiopharmaceuticalRadiationDoseSRStorage_1_2_840_10008_5_1_4_1_1_88_68() {
    return imebraJNI.uidRadiopharmaceuticalRadiationDoseSRStorage_1_2_840_10008_5_1_4_1_1_88_68_get();
  }

  public static String getUidColonCADSRStorage_1_2_840_10008_5_1_4_1_1_88_69() {
    return imebraJNI.uidColonCADSRStorage_1_2_840_10008_5_1_4_1_1_88_69_get();
  }

  public static String getUidImplantationPlanSRStorage_1_2_840_10008_5_1_4_1_1_88_70() {
    return imebraJNI.uidImplantationPlanSRStorage_1_2_840_10008_5_1_4_1_1_88_70_get();
  }

  public static String getUidAcquisitionContextSRStorage_1_2_840_10008_5_1_4_1_1_88_71() {
    return imebraJNI.uidAcquisitionContextSRStorage_1_2_840_10008_5_1_4_1_1_88_71_get();
  }

  public static String getUidSimplifiedAdultEchoSRStorage_1_2_840_10008_5_1_4_1_1_88_72() {
    return imebraJNI.uidSimplifiedAdultEchoSRStorage_1_2_840_10008_5_1_4_1_1_88_72_get();
  }

  public static String getUidPatientRadiationDoseSRStorage_1_2_840_10008_5_1_4_1_1_88_73() {
    return imebraJNI.uidPatientRadiationDoseSRStorage_1_2_840_10008_5_1_4_1_1_88_73_get();
  }

  public static String getUidPlannedImagingAgentAdministrationSRStorage_1_2_840_10008_5_1_4_1_1_88_74() {
    return imebraJNI.uidPlannedImagingAgentAdministrationSRStorage_1_2_840_10008_5_1_4_1_1_88_74_get();
  }

  public static String getUidPerformedImagingAgentAdministrationSRStorage_1_2_840_10008_5_1_4_1_1_88_75() {
    return imebraJNI.uidPerformedImagingAgentAdministrationSRStorage_1_2_840_10008_5_1_4_1_1_88_75_get();
  }

  public static String getUidContentAssessmentResultsStorage_1_2_840_10008_5_1_4_1_1_90_1() {
    return imebraJNI.uidContentAssessmentResultsStorage_1_2_840_10008_5_1_4_1_1_90_1_get();
  }

  public static String getUidEncapsulatedPDFStorage_1_2_840_10008_5_1_4_1_1_104_1() {
    return imebraJNI.uidEncapsulatedPDFStorage_1_2_840_10008_5_1_4_1_1_104_1_get();
  }

  public static String getUidEncapsulatedCDAStorage_1_2_840_10008_5_1_4_1_1_104_2() {
    return imebraJNI.uidEncapsulatedCDAStorage_1_2_840_10008_5_1_4_1_1_104_2_get();
  }

  public static String getUidEncapsulatedSTLStorage_1_2_840_10008_5_1_4_1_1_104_3() {
    return imebraJNI.uidEncapsulatedSTLStorage_1_2_840_10008_5_1_4_1_1_104_3_get();
  }

  public static String getUidPositronEmissionTomographyImageStorage_1_2_840_10008_5_1_4_1_1_128() {
    return imebraJNI.uidPositronEmissionTomographyImageStorage_1_2_840_10008_5_1_4_1_1_128_get();
  }

  public static String getUidLegacyConvertedEnhancedPETImageStorage_1_2_840_10008_5_1_4_1_1_128_1() {
    return imebraJNI.uidLegacyConvertedEnhancedPETImageStorage_1_2_840_10008_5_1_4_1_1_128_1_get();
  }

  public static String getUidStandalonePETCurveStorage_1_2_840_10008_5_1_4_1_1_129() {
    return imebraJNI.uidStandalonePETCurveStorage_1_2_840_10008_5_1_4_1_1_129_get();
  }

  public static String getUidEnhancedPETImageStorage_1_2_840_10008_5_1_4_1_1_130() {
    return imebraJNI.uidEnhancedPETImageStorage_1_2_840_10008_5_1_4_1_1_130_get();
  }

  public static String getUidBasicStructuredDisplayStorage_1_2_840_10008_5_1_4_1_1_131() {
    return imebraJNI.uidBasicStructuredDisplayStorage_1_2_840_10008_5_1_4_1_1_131_get();
  }

  public static String getUidCTDefinedProcedureProtocolStorage_1_2_840_10008_5_1_4_1_1_200_1() {
    return imebraJNI.uidCTDefinedProcedureProtocolStorage_1_2_840_10008_5_1_4_1_1_200_1_get();
  }

  public static String getUidCTPerformedProcedureProtocolStorage_1_2_840_10008_5_1_4_1_1_200_2() {
    return imebraJNI.uidCTPerformedProcedureProtocolStorage_1_2_840_10008_5_1_4_1_1_200_2_get();
  }

  public static String getUidProtocolApprovalStorage_1_2_840_10008_5_1_4_1_1_200_3() {
    return imebraJNI.uidProtocolApprovalStorage_1_2_840_10008_5_1_4_1_1_200_3_get();
  }

  public static String getUidProtocolApprovalInformationModelFIND_1_2_840_10008_5_1_4_1_1_200_4() {
    return imebraJNI.uidProtocolApprovalInformationModelFIND_1_2_840_10008_5_1_4_1_1_200_4_get();
  }

  public static String getUidProtocolApprovalInformationModelMOVE_1_2_840_10008_5_1_4_1_1_200_5() {
    return imebraJNI.uidProtocolApprovalInformationModelMOVE_1_2_840_10008_5_1_4_1_1_200_5_get();
  }

  public static String getUidProtocolApprovalInformationModelGET_1_2_840_10008_5_1_4_1_1_200_6() {
    return imebraJNI.uidProtocolApprovalInformationModelGET_1_2_840_10008_5_1_4_1_1_200_6_get();
  }

  public static String getUidRTImageStorage_1_2_840_10008_5_1_4_1_1_481_1() {
    return imebraJNI.uidRTImageStorage_1_2_840_10008_5_1_4_1_1_481_1_get();
  }

  public static String getUidRTDoseStorage_1_2_840_10008_5_1_4_1_1_481_2() {
    return imebraJNI.uidRTDoseStorage_1_2_840_10008_5_1_4_1_1_481_2_get();
  }

  public static String getUidRTStructureSetStorage_1_2_840_10008_5_1_4_1_1_481_3() {
    return imebraJNI.uidRTStructureSetStorage_1_2_840_10008_5_1_4_1_1_481_3_get();
  }

  public static String getUidRTBeamsTreatmentRecordStorage_1_2_840_10008_5_1_4_1_1_481_4() {
    return imebraJNI.uidRTBeamsTreatmentRecordStorage_1_2_840_10008_5_1_4_1_1_481_4_get();
  }

  public static String getUidRTPlanStorage_1_2_840_10008_5_1_4_1_1_481_5() {
    return imebraJNI.uidRTPlanStorage_1_2_840_10008_5_1_4_1_1_481_5_get();
  }

  public static String getUidRTBrachyTreatmentRecordStorage_1_2_840_10008_5_1_4_1_1_481_6() {
    return imebraJNI.uidRTBrachyTreatmentRecordStorage_1_2_840_10008_5_1_4_1_1_481_6_get();
  }

  public static String getUidRTTreatmentSummaryRecordStorage_1_2_840_10008_5_1_4_1_1_481_7() {
    return imebraJNI.uidRTTreatmentSummaryRecordStorage_1_2_840_10008_5_1_4_1_1_481_7_get();
  }

  public static String getUidRTIonPlanStorage_1_2_840_10008_5_1_4_1_1_481_8() {
    return imebraJNI.uidRTIonPlanStorage_1_2_840_10008_5_1_4_1_1_481_8_get();
  }

  public static String getUidRTIonBeamsTreatmentRecordStorage_1_2_840_10008_5_1_4_1_1_481_9() {
    return imebraJNI.uidRTIonBeamsTreatmentRecordStorage_1_2_840_10008_5_1_4_1_1_481_9_get();
  }

  public static String getUidRTPhysicianIntentStorage_1_2_840_10008_5_1_4_1_1_481_10() {
    return imebraJNI.uidRTPhysicianIntentStorage_1_2_840_10008_5_1_4_1_1_481_10_get();
  }

  public static String getUidRTSegmentAnnotationStorage_1_2_840_10008_5_1_4_1_1_481_11() {
    return imebraJNI.uidRTSegmentAnnotationStorage_1_2_840_10008_5_1_4_1_1_481_11_get();
  }

  public static String getUidDICOSCTImageStorage_1_2_840_10008_5_1_4_1_1_501_1() {
    return imebraJNI.uidDICOSCTImageStorage_1_2_840_10008_5_1_4_1_1_501_1_get();
  }

  public static String getUidDICOSDigitalXRayImageStorageForPresentation_1_2_840_10008_5_1_4_1_1_501_2_1() {
    return imebraJNI.uidDICOSDigitalXRayImageStorageForPresentation_1_2_840_10008_5_1_4_1_1_501_2_1_get();
  }

  public static String getUidDICOSDigitalXRayImageStorageForProcessing_1_2_840_10008_5_1_4_1_1_501_2_2() {
    return imebraJNI.uidDICOSDigitalXRayImageStorageForProcessing_1_2_840_10008_5_1_4_1_1_501_2_2_get();
  }

  public static String getUidDICOSThreatDetectionReportStorage_1_2_840_10008_5_1_4_1_1_501_3() {
    return imebraJNI.uidDICOSThreatDetectionReportStorage_1_2_840_10008_5_1_4_1_1_501_3_get();
  }

  public static String getUidDICOS2DAITStorage_1_2_840_10008_5_1_4_1_1_501_4() {
    return imebraJNI.uidDICOS2DAITStorage_1_2_840_10008_5_1_4_1_1_501_4_get();
  }

  public static String getUidDICOS3DAITStorage_1_2_840_10008_5_1_4_1_1_501_5() {
    return imebraJNI.uidDICOS3DAITStorage_1_2_840_10008_5_1_4_1_1_501_5_get();
  }

  public static String getUidDICOSQuadrupoleResonanceQRStorage_1_2_840_10008_5_1_4_1_1_501_6() {
    return imebraJNI.uidDICOSQuadrupoleResonanceQRStorage_1_2_840_10008_5_1_4_1_1_501_6_get();
  }

  public static String getUidEddyCurrentImageStorage_1_2_840_10008_5_1_4_1_1_601_1() {
    return imebraJNI.uidEddyCurrentImageStorage_1_2_840_10008_5_1_4_1_1_601_1_get();
  }

  public static String getUidEddyCurrentMultiframeImageStorage_1_2_840_10008_5_1_4_1_1_601_2() {
    return imebraJNI.uidEddyCurrentMultiframeImageStorage_1_2_840_10008_5_1_4_1_1_601_2_get();
  }

  public static String getUidPatientRootQueryRetrieveInformationModelFIND_1_2_840_10008_5_1_4_1_2_1_1() {
    return imebraJNI.uidPatientRootQueryRetrieveInformationModelFIND_1_2_840_10008_5_1_4_1_2_1_1_get();
  }

  public static String getUidPatientRootQueryRetrieveInformationModelMOVE_1_2_840_10008_5_1_4_1_2_1_2() {
    return imebraJNI.uidPatientRootQueryRetrieveInformationModelMOVE_1_2_840_10008_5_1_4_1_2_1_2_get();
  }

  public static String getUidPatientRootQueryRetrieveInformationModelGET_1_2_840_10008_5_1_4_1_2_1_3() {
    return imebraJNI.uidPatientRootQueryRetrieveInformationModelGET_1_2_840_10008_5_1_4_1_2_1_3_get();
  }

  public static String getUidStudyRootQueryRetrieveInformationModelFIND_1_2_840_10008_5_1_4_1_2_2_1() {
    return imebraJNI.uidStudyRootQueryRetrieveInformationModelFIND_1_2_840_10008_5_1_4_1_2_2_1_get();
  }

  public static String getUidStudyRootQueryRetrieveInformationModelMOVE_1_2_840_10008_5_1_4_1_2_2_2() {
    return imebraJNI.uidStudyRootQueryRetrieveInformationModelMOVE_1_2_840_10008_5_1_4_1_2_2_2_get();
  }

  public static String getUidStudyRootQueryRetrieveInformationModelGET_1_2_840_10008_5_1_4_1_2_2_3() {
    return imebraJNI.uidStudyRootQueryRetrieveInformationModelGET_1_2_840_10008_5_1_4_1_2_2_3_get();
  }

  public static String getUidPatientStudyOnlyQueryRetrieveInformationModelFIND_1_2_840_10008_5_1_4_1_2_3_1() {
    return imebraJNI.uidPatientStudyOnlyQueryRetrieveInformationModelFIND_1_2_840_10008_5_1_4_1_2_3_1_get();
  }

  public static String getUidPatientStudyOnlyQueryRetrieveInformationModelMOVE_1_2_840_10008_5_1_4_1_2_3_2() {
    return imebraJNI.uidPatientStudyOnlyQueryRetrieveInformationModelMOVE_1_2_840_10008_5_1_4_1_2_3_2_get();
  }

  public static String getUidPatientStudyOnlyQueryRetrieveInformationModelGET_1_2_840_10008_5_1_4_1_2_3_3() {
    return imebraJNI.uidPatientStudyOnlyQueryRetrieveInformationModelGET_1_2_840_10008_5_1_4_1_2_3_3_get();
  }

  public static String getUidCompositeInstanceRootRetrieveMOVE_1_2_840_10008_5_1_4_1_2_4_2() {
    return imebraJNI.uidCompositeInstanceRootRetrieveMOVE_1_2_840_10008_5_1_4_1_2_4_2_get();
  }

  public static String getUidCompositeInstanceRootRetrieveGET_1_2_840_10008_5_1_4_1_2_4_3() {
    return imebraJNI.uidCompositeInstanceRootRetrieveGET_1_2_840_10008_5_1_4_1_2_4_3_get();
  }

  public static String getUidCompositeInstanceRetrieveWithoutBulkDataGET_1_2_840_10008_5_1_4_1_2_5_3() {
    return imebraJNI.uidCompositeInstanceRetrieveWithoutBulkDataGET_1_2_840_10008_5_1_4_1_2_5_3_get();
  }

  public static String getUidDefinedProcedureProtocolInformationModelFIND_1_2_840_10008_5_1_4_20_1() {
    return imebraJNI.uidDefinedProcedureProtocolInformationModelFIND_1_2_840_10008_5_1_4_20_1_get();
  }

  public static String getUidDefinedProcedureProtocolInformationModelMOVE_1_2_840_10008_5_1_4_20_2() {
    return imebraJNI.uidDefinedProcedureProtocolInformationModelMOVE_1_2_840_10008_5_1_4_20_2_get();
  }

  public static String getUidDefinedProcedureProtocolInformationModelGET_1_2_840_10008_5_1_4_20_3() {
    return imebraJNI.uidDefinedProcedureProtocolInformationModelGET_1_2_840_10008_5_1_4_20_3_get();
  }

  public static String getUidModalityWorklistInformationModelFIND_1_2_840_10008_5_1_4_31() {
    return imebraJNI.uidModalityWorklistInformationModelFIND_1_2_840_10008_5_1_4_31_get();
  }

  public static String getUidGeneralPurposeWorklistManagementMetaSOPClass_1_2_840_10008_5_1_4_32() {
    return imebraJNI.uidGeneralPurposeWorklistManagementMetaSOPClass_1_2_840_10008_5_1_4_32_get();
  }

  public static String getUidGeneralPurposeWorklistInformationModelFIND_1_2_840_10008_5_1_4_32_1() {
    return imebraJNI.uidGeneralPurposeWorklistInformationModelFIND_1_2_840_10008_5_1_4_32_1_get();
  }

  public static String getUidGeneralPurposeScheduledProcedureStepSOPClass_1_2_840_10008_5_1_4_32_2() {
    return imebraJNI.uidGeneralPurposeScheduledProcedureStepSOPClass_1_2_840_10008_5_1_4_32_2_get();
  }

  public static String getUidGeneralPurposePerformedProcedureStepSOPClass_1_2_840_10008_5_1_4_32_3() {
    return imebraJNI.uidGeneralPurposePerformedProcedureStepSOPClass_1_2_840_10008_5_1_4_32_3_get();
  }

  public static String getUidInstanceAvailabilityNotificationSOPClass_1_2_840_10008_5_1_4_33() {
    return imebraJNI.uidInstanceAvailabilityNotificationSOPClass_1_2_840_10008_5_1_4_33_get();
  }

  public static String getUidRTBeamsDeliveryInstructionStorageTrial_1_2_840_10008_5_1_4_34_1() {
    return imebraJNI.uidRTBeamsDeliveryInstructionStorageTrial_1_2_840_10008_5_1_4_34_1_get();
  }

  public static String getUidRTConventionalMachineVerificationTrial_1_2_840_10008_5_1_4_34_2() {
    return imebraJNI.uidRTConventionalMachineVerificationTrial_1_2_840_10008_5_1_4_34_2_get();
  }

  public static String getUidRTIonMachineVerificationTrial_1_2_840_10008_5_1_4_34_3() {
    return imebraJNI.uidRTIonMachineVerificationTrial_1_2_840_10008_5_1_4_34_3_get();
  }

  public static String getUidUnifiedWorklistandProcedureStepServiceClassTrial_1_2_840_10008_5_1_4_34_4() {
    return imebraJNI.uidUnifiedWorklistandProcedureStepServiceClassTrial_1_2_840_10008_5_1_4_34_4_get();
  }

  public static String getUidUnifiedProcedureStepPushSOPClassTrial_1_2_840_10008_5_1_4_34_4_1() {
    return imebraJNI.uidUnifiedProcedureStepPushSOPClassTrial_1_2_840_10008_5_1_4_34_4_1_get();
  }

  public static String getUidUnifiedProcedureStepWatchSOPClassTrial_1_2_840_10008_5_1_4_34_4_2() {
    return imebraJNI.uidUnifiedProcedureStepWatchSOPClassTrial_1_2_840_10008_5_1_4_34_4_2_get();
  }

  public static String getUidUnifiedProcedureStepPullSOPClassTrial_1_2_840_10008_5_1_4_34_4_3() {
    return imebraJNI.uidUnifiedProcedureStepPullSOPClassTrial_1_2_840_10008_5_1_4_34_4_3_get();
  }

  public static String getUidUnifiedProcedureStepEventSOPClassTrial_1_2_840_10008_5_1_4_34_4_4() {
    return imebraJNI.uidUnifiedProcedureStepEventSOPClassTrial_1_2_840_10008_5_1_4_34_4_4_get();
  }

  public static String getUidUPSGlobalSubscriptionSOPInstance_1_2_840_10008_5_1_4_34_5() {
    return imebraJNI.uidUPSGlobalSubscriptionSOPInstance_1_2_840_10008_5_1_4_34_5_get();
  }

  public static String getUidUPSFilteredGlobalSubscriptionSOPInstance_1_2_840_10008_5_1_4_34_5_1() {
    return imebraJNI.uidUPSFilteredGlobalSubscriptionSOPInstance_1_2_840_10008_5_1_4_34_5_1_get();
  }

  public static String getUidUnifiedWorklistandProcedureStepServiceClass_1_2_840_10008_5_1_4_34_6() {
    return imebraJNI.uidUnifiedWorklistandProcedureStepServiceClass_1_2_840_10008_5_1_4_34_6_get();
  }

  public static String getUidUnifiedProcedureStepPushSOPClass_1_2_840_10008_5_1_4_34_6_1() {
    return imebraJNI.uidUnifiedProcedureStepPushSOPClass_1_2_840_10008_5_1_4_34_6_1_get();
  }

  public static String getUidUnifiedProcedureStepWatchSOPClass_1_2_840_10008_5_1_4_34_6_2() {
    return imebraJNI.uidUnifiedProcedureStepWatchSOPClass_1_2_840_10008_5_1_4_34_6_2_get();
  }

  public static String getUidUnifiedProcedureStepPullSOPClass_1_2_840_10008_5_1_4_34_6_3() {
    return imebraJNI.uidUnifiedProcedureStepPullSOPClass_1_2_840_10008_5_1_4_34_6_3_get();
  }

  public static String getUidUnifiedProcedureStepEventSOPClass_1_2_840_10008_5_1_4_34_6_4() {
    return imebraJNI.uidUnifiedProcedureStepEventSOPClass_1_2_840_10008_5_1_4_34_6_4_get();
  }

  public static String getUidRTBeamsDeliveryInstructionStorage_1_2_840_10008_5_1_4_34_7() {
    return imebraJNI.uidRTBeamsDeliveryInstructionStorage_1_2_840_10008_5_1_4_34_7_get();
  }

  public static String getUidRTConventionalMachineVerification_1_2_840_10008_5_1_4_34_8() {
    return imebraJNI.uidRTConventionalMachineVerification_1_2_840_10008_5_1_4_34_8_get();
  }

  public static String getUidRTIonMachineVerification_1_2_840_10008_5_1_4_34_9() {
    return imebraJNI.uidRTIonMachineVerification_1_2_840_10008_5_1_4_34_9_get();
  }

  public static String getUidRTBrachyApplicationSetupDeliveryInstructionStorage_1_2_840_10008_5_1_4_34_10() {
    return imebraJNI.uidRTBrachyApplicationSetupDeliveryInstructionStorage_1_2_840_10008_5_1_4_34_10_get();
  }

  public static String getUidGeneralRelevantPatientInformationQuery_1_2_840_10008_5_1_4_37_1() {
    return imebraJNI.uidGeneralRelevantPatientInformationQuery_1_2_840_10008_5_1_4_37_1_get();
  }

  public static String getUidBreastImagingRelevantPatientInformationQuery_1_2_840_10008_5_1_4_37_2() {
    return imebraJNI.uidBreastImagingRelevantPatientInformationQuery_1_2_840_10008_5_1_4_37_2_get();
  }

  public static String getUidCardiacRelevantPatientInformationQuery_1_2_840_10008_5_1_4_37_3() {
    return imebraJNI.uidCardiacRelevantPatientInformationQuery_1_2_840_10008_5_1_4_37_3_get();
  }

  public static String getUidHangingProtocolStorage_1_2_840_10008_5_1_4_38_1() {
    return imebraJNI.uidHangingProtocolStorage_1_2_840_10008_5_1_4_38_1_get();
  }

  public static String getUidHangingProtocolInformationModelFIND_1_2_840_10008_5_1_4_38_2() {
    return imebraJNI.uidHangingProtocolInformationModelFIND_1_2_840_10008_5_1_4_38_2_get();
  }

  public static String getUidHangingProtocolInformationModelMOVE_1_2_840_10008_5_1_4_38_3() {
    return imebraJNI.uidHangingProtocolInformationModelMOVE_1_2_840_10008_5_1_4_38_3_get();
  }

  public static String getUidHangingProtocolInformationModelGET_1_2_840_10008_5_1_4_38_4() {
    return imebraJNI.uidHangingProtocolInformationModelGET_1_2_840_10008_5_1_4_38_4_get();
  }

  public static String getUidColorPaletteStorage_1_2_840_10008_5_1_4_39_1() {
    return imebraJNI.uidColorPaletteStorage_1_2_840_10008_5_1_4_39_1_get();
  }

  public static String getUidColorPaletteQueryRetrieveInformationModelFIND_1_2_840_10008_5_1_4_39_2() {
    return imebraJNI.uidColorPaletteQueryRetrieveInformationModelFIND_1_2_840_10008_5_1_4_39_2_get();
  }

  public static String getUidColorPaletteQueryRetrieveInformationModelMOVE_1_2_840_10008_5_1_4_39_3() {
    return imebraJNI.uidColorPaletteQueryRetrieveInformationModelMOVE_1_2_840_10008_5_1_4_39_3_get();
  }

  public static String getUidColorPaletteQueryRetrieveInformationModelGET_1_2_840_10008_5_1_4_39_4() {
    return imebraJNI.uidColorPaletteQueryRetrieveInformationModelGET_1_2_840_10008_5_1_4_39_4_get();
  }

  public static String getUidProductCharacteristicsQuerySOPClass_1_2_840_10008_5_1_4_41() {
    return imebraJNI.uidProductCharacteristicsQuerySOPClass_1_2_840_10008_5_1_4_41_get();
  }

  public static String getUidSubstanceApprovalQuerySOPClass_1_2_840_10008_5_1_4_42() {
    return imebraJNI.uidSubstanceApprovalQuerySOPClass_1_2_840_10008_5_1_4_42_get();
  }

  public static String getUidGenericImplantTemplateStorage_1_2_840_10008_5_1_4_43_1() {
    return imebraJNI.uidGenericImplantTemplateStorage_1_2_840_10008_5_1_4_43_1_get();
  }

  public static String getUidGenericImplantTemplateInformationModelFIND_1_2_840_10008_5_1_4_43_2() {
    return imebraJNI.uidGenericImplantTemplateInformationModelFIND_1_2_840_10008_5_1_4_43_2_get();
  }

  public static String getUidGenericImplantTemplateInformationModelMOVE_1_2_840_10008_5_1_4_43_3() {
    return imebraJNI.uidGenericImplantTemplateInformationModelMOVE_1_2_840_10008_5_1_4_43_3_get();
  }

  public static String getUidGenericImplantTemplateInformationModelGET_1_2_840_10008_5_1_4_43_4() {
    return imebraJNI.uidGenericImplantTemplateInformationModelGET_1_2_840_10008_5_1_4_43_4_get();
  }

  public static String getUidImplantAssemblyTemplateStorage_1_2_840_10008_5_1_4_44_1() {
    return imebraJNI.uidImplantAssemblyTemplateStorage_1_2_840_10008_5_1_4_44_1_get();
  }

  public static String getUidImplantAssemblyTemplateInformationModelFIND_1_2_840_10008_5_1_4_44_2() {
    return imebraJNI.uidImplantAssemblyTemplateInformationModelFIND_1_2_840_10008_5_1_4_44_2_get();
  }

  public static String getUidImplantAssemblyTemplateInformationModelMOVE_1_2_840_10008_5_1_4_44_3() {
    return imebraJNI.uidImplantAssemblyTemplateInformationModelMOVE_1_2_840_10008_5_1_4_44_3_get();
  }

  public static String getUidImplantAssemblyTemplateInformationModelGET_1_2_840_10008_5_1_4_44_4() {
    return imebraJNI.uidImplantAssemblyTemplateInformationModelGET_1_2_840_10008_5_1_4_44_4_get();
  }

  public static String getUidImplantTemplateGroupStorage_1_2_840_10008_5_1_4_45_1() {
    return imebraJNI.uidImplantTemplateGroupStorage_1_2_840_10008_5_1_4_45_1_get();
  }

  public static String getUidImplantTemplateGroupInformationModelFIND_1_2_840_10008_5_1_4_45_2() {
    return imebraJNI.uidImplantTemplateGroupInformationModelFIND_1_2_840_10008_5_1_4_45_2_get();
  }

  public static String getUidImplantTemplateGroupInformationModelMOVE_1_2_840_10008_5_1_4_45_3() {
    return imebraJNI.uidImplantTemplateGroupInformationModelMOVE_1_2_840_10008_5_1_4_45_3_get();
  }

  public static String getUidImplantTemplateGroupInformationModelGET_1_2_840_10008_5_1_4_45_4() {
    return imebraJNI.uidImplantTemplateGroupInformationModelGET_1_2_840_10008_5_1_4_45_4_get();
  }

  public static String getUidNativeDICOMModel_1_2_840_10008_7_1_1() {
    return imebraJNI.uidNativeDICOMModel_1_2_840_10008_7_1_1_get();
  }

  public static String getUidAbstractMultiDimensionalImageModel_1_2_840_10008_7_1_2() {
    return imebraJNI.uidAbstractMultiDimensionalImageModel_1_2_840_10008_7_1_2_get();
  }

  public static String getUidDICOMContentMappingResource_1_2_840_10008_8_1_1() {
    return imebraJNI.uidDICOMContentMappingResource_1_2_840_10008_8_1_1_get();
  }

  public static String getUiddicomDeviceName_1_2_840_10008_15_0_3_1() {
    return imebraJNI.uiddicomDeviceName_1_2_840_10008_15_0_3_1_get();
  }

  public static String getUiddicomDescription_1_2_840_10008_15_0_3_2() {
    return imebraJNI.uiddicomDescription_1_2_840_10008_15_0_3_2_get();
  }

  public static String getUiddicomManufacturer_1_2_840_10008_15_0_3_3() {
    return imebraJNI.uiddicomManufacturer_1_2_840_10008_15_0_3_3_get();
  }

  public static String getUiddicomManufacturerModelName_1_2_840_10008_15_0_3_4() {
    return imebraJNI.uiddicomManufacturerModelName_1_2_840_10008_15_0_3_4_get();
  }

  public static String getUiddicomSoftwareVersion_1_2_840_10008_15_0_3_5() {
    return imebraJNI.uiddicomSoftwareVersion_1_2_840_10008_15_0_3_5_get();
  }

  public static String getUiddicomVendorData_1_2_840_10008_15_0_3_6() {
    return imebraJNI.uiddicomVendorData_1_2_840_10008_15_0_3_6_get();
  }

  public static String getUiddicomAETitle_1_2_840_10008_15_0_3_7() {
    return imebraJNI.uiddicomAETitle_1_2_840_10008_15_0_3_7_get();
  }

  public static String getUiddicomNetworkConnectionReference_1_2_840_10008_15_0_3_8() {
    return imebraJNI.uiddicomNetworkConnectionReference_1_2_840_10008_15_0_3_8_get();
  }

  public static String getUiddicomApplicationCluster_1_2_840_10008_15_0_3_9() {
    return imebraJNI.uiddicomApplicationCluster_1_2_840_10008_15_0_3_9_get();
  }

  public static String getUiddicomAssociationInitiator_1_2_840_10008_15_0_3_10() {
    return imebraJNI.uiddicomAssociationInitiator_1_2_840_10008_15_0_3_10_get();
  }

  public static String getUiddicomAssociationAcceptor_1_2_840_10008_15_0_3_11() {
    return imebraJNI.uiddicomAssociationAcceptor_1_2_840_10008_15_0_3_11_get();
  }

  public static String getUiddicomHostname_1_2_840_10008_15_0_3_12() {
    return imebraJNI.uiddicomHostname_1_2_840_10008_15_0_3_12_get();
  }

  public static String getUiddicomPort_1_2_840_10008_15_0_3_13() {
    return imebraJNI.uiddicomPort_1_2_840_10008_15_0_3_13_get();
  }

  public static String getUiddicomSOPClass_1_2_840_10008_15_0_3_14() {
    return imebraJNI.uiddicomSOPClass_1_2_840_10008_15_0_3_14_get();
  }

  public static String getUiddicomTransferRole_1_2_840_10008_15_0_3_15() {
    return imebraJNI.uiddicomTransferRole_1_2_840_10008_15_0_3_15_get();
  }

  public static String getUiddicomTransferSyntax_1_2_840_10008_15_0_3_16() {
    return imebraJNI.uiddicomTransferSyntax_1_2_840_10008_15_0_3_16_get();
  }

  public static String getUiddicomPrimaryDeviceType_1_2_840_10008_15_0_3_17() {
    return imebraJNI.uiddicomPrimaryDeviceType_1_2_840_10008_15_0_3_17_get();
  }

  public static String getUiddicomRelatedDeviceReference_1_2_840_10008_15_0_3_18() {
    return imebraJNI.uiddicomRelatedDeviceReference_1_2_840_10008_15_0_3_18_get();
  }

  public static String getUiddicomPreferredCalledAETitle_1_2_840_10008_15_0_3_19() {
    return imebraJNI.uiddicomPreferredCalledAETitle_1_2_840_10008_15_0_3_19_get();
  }

  public static String getUiddicomTLSCyphersuite_1_2_840_10008_15_0_3_20() {
    return imebraJNI.uiddicomTLSCyphersuite_1_2_840_10008_15_0_3_20_get();
  }

  public static String getUiddicomAuthorizedNodeCertificateReference_1_2_840_10008_15_0_3_21() {
    return imebraJNI.uiddicomAuthorizedNodeCertificateReference_1_2_840_10008_15_0_3_21_get();
  }

  public static String getUiddicomThisNodeCertificateReference_1_2_840_10008_15_0_3_22() {
    return imebraJNI.uiddicomThisNodeCertificateReference_1_2_840_10008_15_0_3_22_get();
  }

  public static String getUiddicomInstalled_1_2_840_10008_15_0_3_23() {
    return imebraJNI.uiddicomInstalled_1_2_840_10008_15_0_3_23_get();
  }

  public static String getUiddicomStationName_1_2_840_10008_15_0_3_24() {
    return imebraJNI.uiddicomStationName_1_2_840_10008_15_0_3_24_get();
  }

  public static String getUiddicomDeviceSerialNumber_1_2_840_10008_15_0_3_25() {
    return imebraJNI.uiddicomDeviceSerialNumber_1_2_840_10008_15_0_3_25_get();
  }

  public static String getUiddicomInstitutionName_1_2_840_10008_15_0_3_26() {
    return imebraJNI.uiddicomInstitutionName_1_2_840_10008_15_0_3_26_get();
  }

  public static String getUiddicomInstitutionAddress_1_2_840_10008_15_0_3_27() {
    return imebraJNI.uiddicomInstitutionAddress_1_2_840_10008_15_0_3_27_get();
  }

  public static String getUiddicomInstitutionDepartmentName_1_2_840_10008_15_0_3_28() {
    return imebraJNI.uiddicomInstitutionDepartmentName_1_2_840_10008_15_0_3_28_get();
  }

  public static String getUiddicomIssuerOfPatientID_1_2_840_10008_15_0_3_29() {
    return imebraJNI.uiddicomIssuerOfPatientID_1_2_840_10008_15_0_3_29_get();
  }

  public static String getUiddicomPreferredCallingAETitle_1_2_840_10008_15_0_3_30() {
    return imebraJNI.uiddicomPreferredCallingAETitle_1_2_840_10008_15_0_3_30_get();
  }

  public static String getUiddicomSupportedCharacterSet_1_2_840_10008_15_0_3_31() {
    return imebraJNI.uiddicomSupportedCharacterSet_1_2_840_10008_15_0_3_31_get();
  }

  public static String getUiddicomConfigurationRoot_1_2_840_10008_15_0_4_1() {
    return imebraJNI.uiddicomConfigurationRoot_1_2_840_10008_15_0_4_1_get();
  }

  public static String getUiddicomDevicesRoot_1_2_840_10008_15_0_4_2() {
    return imebraJNI.uiddicomDevicesRoot_1_2_840_10008_15_0_4_2_get();
  }

  public static String getUiddicomUniqueAETitlesRegistryRoot_1_2_840_10008_15_0_4_3() {
    return imebraJNI.uiddicomUniqueAETitlesRegistryRoot_1_2_840_10008_15_0_4_3_get();
  }

  public static String getUiddicomDevice_1_2_840_10008_15_0_4_4() {
    return imebraJNI.uiddicomDevice_1_2_840_10008_15_0_4_4_get();
  }

  public static String getUiddicomNetworkAE_1_2_840_10008_15_0_4_5() {
    return imebraJNI.uiddicomNetworkAE_1_2_840_10008_15_0_4_5_get();
  }

  public static String getUiddicomNetworkConnection_1_2_840_10008_15_0_4_6() {
    return imebraJNI.uiddicomNetworkConnection_1_2_840_10008_15_0_4_6_get();
  }

  public static String getUiddicomUniqueAETitle_1_2_840_10008_15_0_4_7() {
    return imebraJNI.uiddicomUniqueAETitle_1_2_840_10008_15_0_4_7_get();
  }

  public static String getUiddicomTransferCapability_1_2_840_10008_15_0_4_8() {
    return imebraJNI.uiddicomTransferCapability_1_2_840_10008_15_0_4_8_get();
  }

  public static String getUidUniversalCoordinatedTime_1_2_840_10008_15_1_1() {
    return imebraJNI.uidUniversalCoordinatedTime_1_2_840_10008_15_1_1_get();
  }

}
