/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public class LUT {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected LUT(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LUT obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_LUT(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public LUT(LUT source) {
    this(imebraJNI.new_LUT(LUT.getCPtr(source), source), true);
  }

  public SWIGTYPE_p_std__wstring getDescription() {
    return new SWIGTYPE_p_std__wstring(imebraJNI.LUT_getDescription(swigCPtr, this), true);
  }

  public ReadingDataHandlerNumeric getReadingDataHandler() {
    return new ReadingDataHandlerNumeric(imebraJNI.LUT_getReadingDataHandler(swigCPtr, this), true);
  }

  public long getBits() {
    return imebraJNI.LUT_getBits(swigCPtr, this);
  }

  public long getSize() {
    return imebraJNI.LUT_getSize(swigCPtr, this);
  }

  public int getFirstMapped() {
    return imebraJNI.LUT_getFirstMapped(swigCPtr, this);
  }

  public long getMappedValue(int index) {
    return imebraJNI.LUT_getMappedValue(swigCPtr, this, index);
  }

}
