/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public class Memory {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Memory(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Memory obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_Memory(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Memory() {
    this(imebraJNI.new_Memory__SWIG_0(), true);
  }

  public Memory(byte[] source) {
    this(imebraJNI.new_Memory__SWIG_1(source), true);
  }

  public Memory(Memory source) {
    this(imebraJNI.new_Memory__SWIG_2(Memory.getCPtr(source), source), true);
  }

  public long size() {
    return imebraJNI.Memory_size(swigCPtr, this);
  }

  public long data(byte[] destination) {
    return imebraJNI.Memory_data(swigCPtr, this, destination);
  }

  public void regionData(byte[] destination, long sourceOffset) {
    imebraJNI.Memory_regionData(swigCPtr, this, destination, sourceOffset);
  }

  public boolean empty() {
    return imebraJNI.Memory_empty(swigCPtr, this);
  }

}
