/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public class MutableDataSet extends DataSet {
  private transient long swigCPtr;

  protected MutableDataSet(long cPtr, boolean cMemoryOwn) {
    super(imebraJNI.MutableDataSet_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MutableDataSet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_MutableDataSet(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public MutableDataSet(MutableDataSet source) {
    this(imebraJNI.new_MutableDataSet__SWIG_0(MutableDataSet.getCPtr(source), source), true);
  }

  public MutableDataSet() {
    this(imebraJNI.new_MutableDataSet__SWIG_1(), true);
  }

  public MutableDataSet(String transferSyntax) {
    this(imebraJNI.new_MutableDataSet__SWIG_2(transferSyntax), true);
  }

  public MutableDataSet(String transferSyntax, StringsList charsets) {
    this(imebraJNI.new_MutableDataSet__SWIG_3(transferSyntax, StringsList.getCPtr(charsets), charsets), true);
  }

  public MutableTag getTagCreate(TagId tagId, tagVR_t tagVR) {
    return new MutableTag(imebraJNI.MutableDataSet_getTagCreate__SWIG_0(swigCPtr, this, TagId.getCPtr(tagId), tagId, tagVR.swigValue()), true);
  }

  public MutableTag getTagCreate(TagId tagId) {
    return new MutableTag(imebraJNI.MutableDataSet_getTagCreate__SWIG_1(swigCPtr, this, TagId.getCPtr(tagId), tagId), true);
  }

  public void setImage(long frameNumber, Image image, imageQuality_t quality) {
    imebraJNI.MutableDataSet_setImage(swigCPtr, this, frameNumber, Image.getCPtr(image), image, quality.swigValue());
  }

  public void setOverlay(long overlayNumber, Overlay overlay) {
    imebraJNI.MutableDataSet_setOverlay(swigCPtr, this, overlayNumber, Overlay.getCPtr(overlay), overlay);
  }

  public StreamWriter getStreamWriter(TagId tagId, long bufferId, tagVR_t tagVR) {
    return new StreamWriter(imebraJNI.MutableDataSet_getStreamWriter__SWIG_0(swigCPtr, this, TagId.getCPtr(tagId), tagId, bufferId, tagVR.swigValue()), true);
  }

  public StreamWriter getStreamWriter(TagId tagId, long bufferId) {
    return new StreamWriter(imebraJNI.MutableDataSet_getStreamWriter__SWIG_1(swigCPtr, this, TagId.getCPtr(tagId), tagId, bufferId), true);
  }

  public MutableDataSet appendSequenceItem(TagId tagId) {
    return new MutableDataSet(imebraJNI.MutableDataSet_appendSequenceItem(swigCPtr, this, TagId.getCPtr(tagId), tagId), true);
  }

  public WritingDataHandler getWritingDataHandler(TagId tagId, long bufferId, tagVR_t tagVR) {
    return new WritingDataHandler(imebraJNI.MutableDataSet_getWritingDataHandler__SWIG_0(swigCPtr, this, TagId.getCPtr(tagId), tagId, bufferId, tagVR.swigValue()), true);
  }

  public WritingDataHandler getWritingDataHandler(TagId tagId, long bufferId) {
    return new WritingDataHandler(imebraJNI.MutableDataSet_getWritingDataHandler__SWIG_1(swigCPtr, this, TagId.getCPtr(tagId), tagId, bufferId), true);
  }

  public WritingDataHandlerNumeric getWritingDataHandlerNumeric(TagId tagId, long bufferId, tagVR_t tagVR) {
    return new WritingDataHandlerNumeric(imebraJNI.MutableDataSet_getWritingDataHandlerNumeric__SWIG_0(swigCPtr, this, TagId.getCPtr(tagId), tagId, bufferId, tagVR.swigValue()), true);
  }

  public WritingDataHandlerNumeric getWritingDataHandlerNumeric(TagId tagId, long bufferId) {
    return new WritingDataHandlerNumeric(imebraJNI.MutableDataSet_getWritingDataHandlerNumeric__SWIG_1(swigCPtr, this, TagId.getCPtr(tagId), tagId, bufferId), true);
  }

  public WritingDataHandlerNumeric getWritingDataHandlerRaw(TagId tagId, long bufferId, tagVR_t tagVR) {
    return new WritingDataHandlerNumeric(imebraJNI.MutableDataSet_getWritingDataHandlerRaw__SWIG_0(swigCPtr, this, TagId.getCPtr(tagId), tagId, bufferId, tagVR.swigValue()), true);
  }

  public WritingDataHandlerNumeric getWritingDataHandlerRaw(TagId tagId, long bufferId) {
    return new WritingDataHandlerNumeric(imebraJNI.MutableDataSet_getWritingDataHandlerRaw__SWIG_1(swigCPtr, this, TagId.getCPtr(tagId), tagId, bufferId), true);
  }

  public void setInt32(TagId tagId, int newValue, tagVR_t tagVR) {
    imebraJNI.MutableDataSet_setInt32__SWIG_0(swigCPtr, this, TagId.getCPtr(tagId), tagId, newValue, tagVR.swigValue());
  }

  public void setSignedLong(TagId tagId, int newValue, tagVR_t tagVR) {
    imebraJNI.MutableDataSet_setSignedLong__SWIG_0(swigCPtr, this, TagId.getCPtr(tagId), tagId, newValue, tagVR.swigValue());
  }

  public void setInt32(TagId tagId, int newValue) {
    imebraJNI.MutableDataSet_setInt32__SWIG_1(swigCPtr, this, TagId.getCPtr(tagId), tagId, newValue);
  }

  public void setSignedLong(TagId tagId, int newValue) {
    imebraJNI.MutableDataSet_setSignedLong__SWIG_1(swigCPtr, this, TagId.getCPtr(tagId), tagId, newValue);
  }

  public void setUint32(TagId tagId, long newValue, tagVR_t tagVR) {
    imebraJNI.MutableDataSet_setUint32__SWIG_0(swigCPtr, this, TagId.getCPtr(tagId), tagId, newValue, tagVR.swigValue());
  }

  public void setUnsignedLong(TagId tagId, long newValue, tagVR_t tagVR) {
    imebraJNI.MutableDataSet_setUnsignedLong__SWIG_0(swigCPtr, this, TagId.getCPtr(tagId), tagId, newValue, tagVR.swigValue());
  }

  public void setUint32(TagId tagId, long newValue) {
    imebraJNI.MutableDataSet_setUint32__SWIG_1(swigCPtr, this, TagId.getCPtr(tagId), tagId, newValue);
  }

  public void setUnsignedLong(TagId tagId, long newValue) {
    imebraJNI.MutableDataSet_setUnsignedLong__SWIG_1(swigCPtr, this, TagId.getCPtr(tagId), tagId, newValue);
  }

  public void setInt16(TagId tagId, short newValue, tagVR_t tagVR) {
    imebraJNI.MutableDataSet_setInt16__SWIG_0(swigCPtr, this, TagId.getCPtr(tagId), tagId, newValue, tagVR.swigValue());
  }

  public void setInt16(TagId tagId, short newValue) {
    imebraJNI.MutableDataSet_setInt16__SWIG_1(swigCPtr, this, TagId.getCPtr(tagId), tagId, newValue);
  }

  public void setUint16(TagId tagId, int newValue, tagVR_t tagVR) {
    imebraJNI.MutableDataSet_setUint16__SWIG_0(swigCPtr, this, TagId.getCPtr(tagId), tagId, newValue, tagVR.swigValue());
  }

  public void setUint16(TagId tagId, int newValue) {
    imebraJNI.MutableDataSet_setUint16__SWIG_1(swigCPtr, this, TagId.getCPtr(tagId), tagId, newValue);
  }

  public void setInt8(TagId tagId, byte newValue, tagVR_t tagVR) {
    imebraJNI.MutableDataSet_setInt8__SWIG_0(swigCPtr, this, TagId.getCPtr(tagId), tagId, newValue, tagVR.swigValue());
  }

  public void setInt8(TagId tagId, byte newValue) {
    imebraJNI.MutableDataSet_setInt8__SWIG_1(swigCPtr, this, TagId.getCPtr(tagId), tagId, newValue);
  }

  public void setUint8(TagId tagId, short newValue, tagVR_t tagVR) {
    imebraJNI.MutableDataSet_setUint8__SWIG_0(swigCPtr, this, TagId.getCPtr(tagId), tagId, newValue, tagVR.swigValue());
  }

  public void setUint8(TagId tagId, short newValue) {
    imebraJNI.MutableDataSet_setUint8__SWIG_1(swigCPtr, this, TagId.getCPtr(tagId), tagId, newValue);
  }

  public void setDouble(TagId tagId, double newValue, tagVR_t tagVR) {
    imebraJNI.MutableDataSet_setDouble__SWIG_0(swigCPtr, this, TagId.getCPtr(tagId), tagId, newValue, tagVR.swigValue());
  }

  public void setDouble(TagId tagId, double newValue) {
    imebraJNI.MutableDataSet_setDouble__SWIG_1(swigCPtr, this, TagId.getCPtr(tagId), tagId, newValue);
  }

  public void setFloat(TagId tagId, float newValue, tagVR_t tagVR) {
    imebraJNI.MutableDataSet_setFloat__SWIG_0(swigCPtr, this, TagId.getCPtr(tagId), tagId, newValue, tagVR.swigValue());
  }

  public void setFloat(TagId tagId, float newValue) {
    imebraJNI.MutableDataSet_setFloat__SWIG_1(swigCPtr, this, TagId.getCPtr(tagId), tagId, newValue);
  }

  public void setString(TagId tagId, String newString, tagVR_t tagVR) {
    imebraJNI.MutableDataSet_setString__SWIG_0(swigCPtr, this, TagId.getCPtr(tagId), tagId, newString, tagVR.swigValue());
  }

  public void setString(TagId tagId, String newString) {
    imebraJNI.MutableDataSet_setString__SWIG_1(swigCPtr, this, TagId.getCPtr(tagId), tagId, newString);
  }

  public void setAge(TagId tagId, Age age) {
    imebraJNI.MutableDataSet_setAge(swigCPtr, this, TagId.getCPtr(tagId), tagId, Age.getCPtr(age), age);
  }

  public void setDate(TagId tagId, Date date, tagVR_t tagVR) {
    imebraJNI.MutableDataSet_setDate__SWIG_0(swigCPtr, this, TagId.getCPtr(tagId), tagId, Date.getCPtr(date), date, tagVR.swigValue());
  }

  public void setDate(TagId tagId, Date date) {
    imebraJNI.MutableDataSet_setDate__SWIG_1(swigCPtr, this, TagId.getCPtr(tagId), tagId, Date.getCPtr(date), date);
  }

  public void setPatientName(TagId tagId, PatientName patientName) {
    imebraJNI.MutableDataSet_setPatientName(swigCPtr, this, TagId.getCPtr(tagId), tagId, PatientName.getCPtr(patientName), patientName);
  }

}
