/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public class MutableDicomDir extends DicomDir {
  private transient long swigCPtr;

  protected MutableDicomDir(long cPtr, boolean cMemoryOwn) {
    super(imebraJNI.MutableDicomDir_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MutableDicomDir obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_MutableDicomDir(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public MutableDicomDir() {
    this(imebraJNI.new_MutableDicomDir__SWIG_0(), true);
  }

  public MutableDicomDir(MutableDataSet fromDataSet) {
    this(imebraJNI.new_MutableDicomDir__SWIG_1(MutableDataSet.getCPtr(fromDataSet), fromDataSet), true);
  }

  public MutableDicomDir(MutableDicomDir source) {
    this(imebraJNI.new_MutableDicomDir__SWIG_2(MutableDicomDir.getCPtr(source), source), true);
  }

  public MutableDicomDirEntry getNewEntry(String recordType) {
    return new MutableDicomDirEntry(imebraJNI.MutableDicomDir_getNewEntry(swigCPtr, this, recordType), true);
  }

  public void setFirstRootEntry(DicomDirEntry firstEntryRecord) {
    imebraJNI.MutableDicomDir_setFirstRootEntry(swigCPtr, this, DicomDirEntry.getCPtr(firstEntryRecord), firstEntryRecord);
  }

  public DataSet updateDataSet() {
    return new DataSet(imebraJNI.MutableDicomDir_updateDataSet(swigCPtr, this), true);
  }

}
