/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public class MutableImage extends Image {
  private transient long swigCPtr;

  protected MutableImage(long cPtr, boolean cMemoryOwn) {
    super(imebraJNI.MutableImage_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MutableImage obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_MutableImage(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public MutableImage(long width, long height, bitDepth_t depth, String colorSpace, long highBit) {
    this(imebraJNI.new_MutableImage__SWIG_0(width, height, depth.swigValue(), colorSpace, highBit), true);
  }

  public MutableImage(MutableImage source) {
    this(imebraJNI.new_MutableImage__SWIG_1(MutableImage.getCPtr(source), source), true);
  }

  public WritingDataHandlerNumeric getWritingDataHandler() {
    return new WritingDataHandlerNumeric(imebraJNI.MutableImage_getWritingDataHandler(swigCPtr, this), true);
  }

}
