/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public class NActionCommand extends DimseCommand {
  private transient long swigCPtr;

  protected NActionCommand(long cPtr, boolean cMemoryOwn) {
    super(imebraJNI.NActionCommand_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NActionCommand obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_NActionCommand(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public NActionCommand(String abstractSyntax, int messageID, String requestedSopClassUid, String requestedSopInstanceUid, int actionID, DataSet actionInformation) {
    this(imebraJNI.new_NActionCommand__SWIG_0(abstractSyntax, messageID, requestedSopClassUid, requestedSopInstanceUid, actionID, DataSet.getCPtr(actionInformation), actionInformation), true);
  }

  public NActionCommand(String abstractSyntax, int messageID, String requestedSopClassUid, String requestedSopInstanceUid, int actionID) {
    this(imebraJNI.new_NActionCommand__SWIG_1(abstractSyntax, messageID, requestedSopClassUid, requestedSopInstanceUid, actionID), true);
  }

  public NActionCommand(NActionCommand source) {
    this(imebraJNI.new_NActionCommand__SWIG_2(NActionCommand.getCPtr(source), source), true);
  }

  public int getActionID() {
    return imebraJNI.NActionCommand_getActionID(swigCPtr, this);
  }

}
