/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public class NActionResponse extends DimseResponse {
  private transient long swigCPtr;

  protected NActionResponse(long cPtr, boolean cMemoryOwn) {
    super(imebraJNI.NActionResponse_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NActionResponse obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_NActionResponse(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public NActionResponse(NActionCommand receivedCommand, DataSet actionReply) {
    this(imebraJNI.new_NActionResponse__SWIG_0(NActionCommand.getCPtr(receivedCommand), receivedCommand, DataSet.getCPtr(actionReply), actionReply), true);
  }

  public NActionResponse(NActionCommand receivedCommand, dimseStatusCode_t responseCode) {
    this(imebraJNI.new_NActionResponse__SWIG_1(NActionCommand.getCPtr(receivedCommand), receivedCommand, responseCode.swigValue()), true);
  }

  public NActionResponse(NActionResponse source) {
    this(imebraJNI.new_NActionResponse__SWIG_2(NActionResponse.getCPtr(source), source), true);
  }

  public int getActionID() {
    return imebraJNI.NActionResponse_getActionID(swigCPtr, this);
  }

}
