/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public class NCreateCommand extends DimseCommand {
  private transient long swigCPtr;

  protected NCreateCommand(long cPtr, boolean cMemoryOwn) {
    super(imebraJNI.NCreateCommand_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NCreateCommand obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_NCreateCommand(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public NCreateCommand(String abstractSyntax, int messageID, String affectedSopClassUid, String affectedSopInstanceUid, DataSet attributeList) {
    this(imebraJNI.new_NCreateCommand__SWIG_0(abstractSyntax, messageID, affectedSopClassUid, affectedSopInstanceUid, DataSet.getCPtr(attributeList), attributeList), true);
  }

  public NCreateCommand(String abstractSyntax, int messageID, String affectedSopClassUid, String affectedSopInstanceUid) {
    this(imebraJNI.new_NCreateCommand__SWIG_1(abstractSyntax, messageID, affectedSopClassUid, affectedSopInstanceUid), true);
  }

  public NCreateCommand(NCreateCommand source) {
    this(imebraJNI.new_NCreateCommand__SWIG_2(NCreateCommand.getCPtr(source), source), true);
  }

}
