/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public class NDeleteResponse extends DimseResponse {
  private transient long swigCPtr;

  protected NDeleteResponse(long cPtr, boolean cMemoryOwn) {
    super(imebraJNI.NDeleteResponse_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NDeleteResponse obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_NDeleteResponse(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public NDeleteResponse(NDeleteCommand receivedCommand, dimseStatusCode_t responseCode) {
    this(imebraJNI.new_NDeleteResponse__SWIG_0(NDeleteCommand.getCPtr(receivedCommand), receivedCommand, responseCode.swigValue()), true);
  }

  public NDeleteResponse(NDeleteResponse source) {
    this(imebraJNI.new_NDeleteResponse__SWIG_1(NDeleteResponse.getCPtr(source), source), true);
  }

}
