/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public class NDeleteCommand extends DimseCommand {
  private transient long swigCPtr;

  protected NDeleteCommand(long cPtr, boolean cMemoryOwn) {
    super(imebraJNI.NDeleteCommand_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NDeleteCommand obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_NDeleteCommand(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public NDeleteCommand(String abstractSyntax, int messageID, String requestedSopClassUid, String requestedSopInstanceUid) {
    this(imebraJNI.new_NDeleteCommand__SWIG_0(abstractSyntax, messageID, requestedSopClassUid, requestedSopInstanceUid), true);
  }

  public NDeleteCommand(NDeleteCommand source) {
    this(imebraJNI.new_NDeleteCommand__SWIG_1(NDeleteCommand.getCPtr(source), source), true);
  }

}
