/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public class NEventReportResponse extends DimseResponse {
  private transient long swigCPtr;

  protected NEventReportResponse(long cPtr, boolean cMemoryOwn) {
    super(imebraJNI.NEventReportResponse_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NEventReportResponse obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_NEventReportResponse(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public NEventReportResponse(NEventReportCommand receivedCommand, DataSet eventReply) {
    this(imebraJNI.new_NEventReportResponse__SWIG_0(NEventReportCommand.getCPtr(receivedCommand), receivedCommand, DataSet.getCPtr(eventReply), eventReply), true);
  }

  public NEventReportResponse(NEventReportCommand receivedCommand, dimseStatusCode_t responseCode) {
    this(imebraJNI.new_NEventReportResponse__SWIG_1(NEventReportCommand.getCPtr(receivedCommand), receivedCommand, responseCode.swigValue()), true);
  }

  public NEventReportResponse(NEventReportResponse source) {
    this(imebraJNI.new_NEventReportResponse__SWIG_2(NEventReportResponse.getCPtr(source), source), true);
  }

  public int getEventID() {
    return imebraJNI.NEventReportResponse_getEventID(swigCPtr, this);
  }

}
