/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public class NEventReportCommand extends DimseCommand {
  private transient long swigCPtr;

  protected NEventReportCommand(long cPtr, boolean cMemoryOwn) {
    super(imebraJNI.NEventReportCommand_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NEventReportCommand obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_NEventReportCommand(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public NEventReportCommand(String abstractSyntax, int messageID, String affectedSopClassUid, String affectedSopInstanceUid, int eventID) {
    this(imebraJNI.new_NEventReportCommand__SWIG_0(abstractSyntax, messageID, affectedSopClassUid, affectedSopInstanceUid, eventID), true);
  }

  public NEventReportCommand(String abstractSyntax, int messageID, String affectedSopClassUid, String affectedSopInstanceUid, int eventID, DataSet eventInformation) {
    this(imebraJNI.new_NEventReportCommand__SWIG_1(abstractSyntax, messageID, affectedSopClassUid, affectedSopInstanceUid, eventID, DataSet.getCPtr(eventInformation), eventInformation), true);
  }

  public NEventReportCommand(NEventReportCommand source) {
    this(imebraJNI.new_NEventReportCommand__SWIG_2(NEventReportCommand.getCPtr(source), source), true);
  }

  public int getEventID() {
    return imebraJNI.NEventReportCommand_getEventID(swigCPtr, this);
  }

}
