/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public class NSetResponse extends DimseResponse {
  private transient long swigCPtr;

  protected NSetResponse(long cPtr, boolean cMemoryOwn) {
    super(imebraJNI.NSetResponse_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NSetResponse obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_NSetResponse(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public NSetResponse(NSetCommand receivedCommand, SWIGTYPE_p_std__vectorT_unsigned_int_t modifiedAttributes) {
    this(imebraJNI.new_NSetResponse__SWIG_0(NSetCommand.getCPtr(receivedCommand), receivedCommand, SWIGTYPE_p_std__vectorT_unsigned_int_t.getCPtr(modifiedAttributes)), true);
  }

  public NSetResponse(NSetCommand receivedCommand, dimseStatusCode_t responseCode) {
    this(imebraJNI.new_NSetResponse__SWIG_1(NSetCommand.getCPtr(receivedCommand), receivedCommand, responseCode.swigValue()), true);
  }

  public NSetResponse(NSetResponse source) {
    this(imebraJNI.new_NSetResponse__SWIG_2(NSetResponse.getCPtr(source), source), true);
  }

  public SWIGTYPE_p_std__vectorT_unsigned_int_t getModifiedAttributes() {
    return new SWIGTYPE_p_std__vectorT_unsigned_int_t(imebraJNI.NSetResponse_getModifiedAttributes(swigCPtr, this), true);
  }

}
