/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public class NSetCommand extends DimseCommand {
  private transient long swigCPtr;

  protected NSetCommand(long cPtr, boolean cMemoryOwn) {
    super(imebraJNI.NSetCommand_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NSetCommand obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_NSetCommand(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public NSetCommand(String abstractSyntax, int messageID, String requestedSopClassUid, String requestedSopInstanceUid, DataSet modificationList) {
    this(imebraJNI.new_NSetCommand__SWIG_0(abstractSyntax, messageID, requestedSopClassUid, requestedSopInstanceUid, DataSet.getCPtr(modificationList), modificationList), true);
  }

  public NSetCommand(NSetCommand source) {
    this(imebraJNI.new_NSetCommand__SWIG_1(NSetCommand.getCPtr(source), source), true);
  }

}
