/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public enum overlayType_t {
  graphic(imebraJNI.overlayType_t_graphic_get()),
  ROI(imebraJNI.overlayType_t_ROI_get());

  public final int swigValue() {
    return swigValue;
  }

  public static overlayType_t swigToEnum(int swigValue) {
    overlayType_t[] swigValues = overlayType_t.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (overlayType_t swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + overlayType_t.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private overlayType_t() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private overlayType_t(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private overlayType_t(overlayType_t swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

