/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public class PipeStream {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected PipeStream(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PipeStream obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_PipeStream(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PipeStream(long circularBufferSize) {
    this(imebraJNI.new_PipeStream__SWIG_0(circularBufferSize), true);
  }

  public PipeStream(PipeStream source) {
    this(imebraJNI.new_PipeStream__SWIG_1(PipeStream.getCPtr(source), source), true);
  }

  public void close(long timeoutMilliseconds) {
    imebraJNI.PipeStream_close(swigCPtr, this, timeoutMilliseconds);
  }

  public BaseStreamInput getStreamInput() {
    return new BaseStreamInput(imebraJNI.PipeStream_getStreamInput(swigCPtr, this), true);
  }

  public BaseStreamOutput getStreamOutput() {
    return new BaseStreamOutput(imebraJNI.PipeStream_getStreamOutput(swigCPtr, this), true);
  }

}
