/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public class RandomUIDGenerator extends BaseUIDGenerator {
  private transient long swigCPtr;

  protected RandomUIDGenerator(long cPtr, boolean cMemoryOwn) {
    super(imebraJNI.RandomUIDGenerator_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RandomUIDGenerator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_RandomUIDGenerator(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public RandomUIDGenerator(String root, long departmentId, long modelId) {
    this(imebraJNI.new_RandomUIDGenerator__SWIG_0(root, departmentId, modelId), true);
  }

  public RandomUIDGenerator(RandomUIDGenerator source) {
    this(imebraJNI.new_RandomUIDGenerator__SWIG_1(RandomUIDGenerator.getCPtr(source), source), true);
  }

}
