/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public class ReadingDataHandlerNumeric extends ReadingDataHandler {
  private transient long swigCPtr;

  protected ReadingDataHandlerNumeric(long cPtr, boolean cMemoryOwn) {
    super(imebraJNI.ReadingDataHandlerNumeric_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ReadingDataHandlerNumeric obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_ReadingDataHandlerNumeric(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ReadingDataHandlerNumeric(ReadingDataHandlerNumeric source) {
    this(imebraJNI.new_ReadingDataHandlerNumeric(ReadingDataHandlerNumeric.getCPtr(source), source), true);
  }

  public Memory getMemory() {
    return new Memory(imebraJNI.ReadingDataHandlerNumeric_getMemory(swigCPtr, this), true);
  }

  public long data(byte[] destination) {
    return imebraJNI.ReadingDataHandlerNumeric_data(swigCPtr, this, destination);
  }

  public long getUnitSize() {
    return imebraJNI.ReadingDataHandlerNumeric_getUnitSize(swigCPtr, this);
  }

  public boolean isSigned() {
    return imebraJNI.ReadingDataHandlerNumeric_isSigned(swigCPtr, this);
  }

  public boolean isFloat() {
    return imebraJNI.ReadingDataHandlerNumeric_isFloat(swigCPtr, this);
  }

  public void copyTo(WritingDataHandlerNumeric destination) {
    imebraJNI.ReadingDataHandlerNumeric_copyTo(swigCPtr, this, WritingDataHandlerNumeric.getCPtr(destination), destination);
  }

}
