/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public class StreamWriter {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StreamWriter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StreamWriter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_StreamWriter(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public StreamWriter(BaseStreamOutput stream) {
    this(imebraJNI.new_StreamWriter__SWIG_0(BaseStreamOutput.getCPtr(stream), stream), true);
  }

  public StreamWriter(BaseStreamOutput stream, long virtualStart, long virtualLength) {
    this(imebraJNI.new_StreamWriter__SWIG_1(BaseStreamOutput.getCPtr(stream), stream, virtualStart, virtualLength), true);
  }

  public StreamWriter(StreamWriter source) {
    this(imebraJNI.new_StreamWriter__SWIG_2(StreamWriter.getCPtr(source), source), true);
  }

  public void write(String data, long dataSize) {
    imebraJNI.StreamWriter_write__SWIG_0(swigCPtr, this, data, dataSize);
  }

  public void write(Memory memory) {
    imebraJNI.StreamWriter_write__SWIG_1(swigCPtr, this, Memory.getCPtr(memory), memory);
  }

  public void flush() {
    imebraJNI.StreamWriter_flush(swigCPtr, this);
  }

}
