/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public class StreamReader {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StreamReader(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StreamReader obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_StreamReader(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public StreamReader(BaseStreamInput stream) {
    this(imebraJNI.new_StreamReader__SWIG_0(BaseStreamInput.getCPtr(stream), stream), true);
  }

  public StreamReader(BaseStreamInput stream, long virtualStart, long virtualLength) {
    this(imebraJNI.new_StreamReader__SWIG_1(BaseStreamInput.getCPtr(stream), stream, virtualStart, virtualLength), true);
  }

  public StreamReader(StreamReader source) {
    this(imebraJNI.new_StreamReader__SWIG_2(StreamReader.getCPtr(source), source), true);
  }

  public StreamReader getVirtualStream(long virtualStreamLength) {
    return new StreamReader(imebraJNI.StreamReader_getVirtualStream(swigCPtr, this, virtualStreamLength), true);
  }

  public void read(byte[] destination) {
    imebraJNI.StreamReader_read__SWIG_0(swigCPtr, this, destination);
  }

  public long readSome(byte[] destination) {
    return imebraJNI.StreamReader_readSome__SWIG_0(swigCPtr, this, destination);
  }

  public Memory read(long readSize) {
    return new Memory(imebraJNI.StreamReader_read__SWIG_1(swigCPtr, this, readSize), true);
  }

  public Memory readSome(long readSize) {
    return new Memory(imebraJNI.StreamReader_readSome__SWIG_1(swigCPtr, this, readSize), true);
  }

  public void terminate() {
    imebraJNI.StreamReader_terminate(swigCPtr, this);
  }

}
