/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public class TagsIds extends java.util.AbstractList<TagId> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TagsIds(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TagsIds obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_TagsIds(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TagsIds(TagId[] initialElements) {
    this();
    reserve(initialElements.length);

    for (TagId element : initialElements) {
      add(element);
    }
  }

  public TagsIds(Iterable<TagId> initialElements) {
    this();
    for (TagId element : initialElements) {
      add(element);
    }
  }

  public TagId get(int index) {
    return doGet(index);
  }

  public TagId set(int index, TagId e) {
    return doSet(index, e);
  }

  public boolean add(TagId e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, TagId e) {
    modCount++;
    doAdd(index, e);
  }

  public TagId remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public TagsIds() {
    this(imebraJNI.new_TagsIds__SWIG_0(), true);
  }

  public TagsIds(TagsIds other) {
    this(imebraJNI.new_TagsIds__SWIG_1(TagsIds.getCPtr(other), other), true);
  }

  public long capacity() {
    return imebraJNI.TagsIds_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    imebraJNI.TagsIds_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return imebraJNI.TagsIds_isEmpty(swigCPtr, this);
  }

  public void clear() {
    imebraJNI.TagsIds_clear(swigCPtr, this);
  }

  public TagsIds(int count, TagId value) {
    this(imebraJNI.new_TagsIds__SWIG_2(count, TagId.getCPtr(value), value), true);
  }

  private int doSize() {
    return imebraJNI.TagsIds_doSize(swigCPtr, this);
  }

  private void doAdd(TagId x) {
    imebraJNI.TagsIds_doAdd__SWIG_0(swigCPtr, this, TagId.getCPtr(x), x);
  }

  private void doAdd(int index, TagId x) {
    imebraJNI.TagsIds_doAdd__SWIG_1(swigCPtr, this, index, TagId.getCPtr(x), x);
  }

  private TagId doRemove(int index) {
    return new TagId(imebraJNI.TagsIds_doRemove(swigCPtr, this, index), true);
  }

  private TagId doGet(int index) {
    return new TagId(imebraJNI.TagsIds_doGet(swigCPtr, this, index), false);
  }

  private TagId doSet(int index, TagId val) {
    return new TagId(imebraJNI.TagsIds_doSet(swigCPtr, this, index, TagId.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    imebraJNI.TagsIds_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
