/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public class TCPAddress {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TCPAddress(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TCPAddress obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_TCPAddress(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TCPAddress(TCPAddress source) {
    this(imebraJNI.new_TCPAddress(TCPAddress.getCPtr(source), source), true);
  }

  public String getNode() {
    return imebraJNI.TCPAddress_getNode(swigCPtr, this);
  }

  public String getService() {
    return imebraJNI.TCPAddress_getService(swigCPtr, this);
  }

}
