/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public class TCPStream {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TCPStream(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TCPStream obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_TCPStream(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TCPStream(TCPActiveAddress address) {
    this(imebraJNI.new_TCPStream__SWIG_0(TCPActiveAddress.getCPtr(address), address), true);
  }

  public TCPStream(TCPStream source) {
    this(imebraJNI.new_TCPStream__SWIG_1(TCPStream.getCPtr(source), source), true);
  }

  public TCPAddress getPeerAddress() {
    return new TCPAddress(imebraJNI.TCPStream_getPeerAddress(swigCPtr, this), true);
  }

  public BaseStreamInput getStreamInput() {
    return new BaseStreamInput(imebraJNI.TCPStream_getStreamInput(swigCPtr, this), true);
  }

  public BaseStreamOutput getStreamOutput() {
    return new BaseStreamOutput(imebraJNI.TCPStream_getStreamOutput(swigCPtr, this), true);
  }

}
