/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public class Transform {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Transform(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Transform obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_Transform(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Transform(Transform source) {
    this(imebraJNI.new_Transform(Transform.getCPtr(source), source), true);
  }

  public boolean isEmpty() {
    return imebraJNI.Transform_isEmpty(swigCPtr, this);
  }

  public MutableImage allocateOutputImage(Image inputImage, long width, long height) {
    return new MutableImage(imebraJNI.Transform_allocateOutputImage(swigCPtr, this, Image.getCPtr(inputImage), inputImage, width, height), true);
  }

  public void runTransform(Image inputImage, long inputTopLeftX, long inputTopLeftY, long inputWidth, long inputHeight, MutableImage outputImage, long outputTopLeftX, long outputTopLeftY) {
    imebraJNI.Transform_runTransform(swigCPtr, this, Image.getCPtr(inputImage), inputImage, inputTopLeftX, inputTopLeftY, inputWidth, inputHeight, MutableImage.getCPtr(outputImage), outputImage, outputTopLeftX, outputTopLeftY);
  }

}
