/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public class UIDGeneratorFactory {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected UIDGeneratorFactory(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UIDGeneratorFactory obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_UIDGeneratorFactory(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static void registerUIDGenerator(String name, BaseUIDGenerator uidGenerator) {
    imebraJNI.UIDGeneratorFactory_registerUIDGenerator(name, BaseUIDGenerator.getCPtr(uidGenerator), uidGenerator);
  }

  public static BaseUIDGenerator getUIDGenerator(String name) {
    return new BaseUIDGenerator(imebraJNI.UIDGeneratorFactory_getUIDGenerator(name), true);
  }

  public static BaseUIDGenerator getDefaultUIDGenerator() {
    return new BaseUIDGenerator(imebraJNI.UIDGeneratorFactory_getDefaultUIDGenerator(), true);
  }

  public UIDGeneratorFactory() {
    this(imebraJNI.new_UIDGeneratorFactory(), true);
  }

}
