/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.imebra;

public class VOIDescription {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VOIDescription(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VOIDescription obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        imebraJNI.delete_VOIDescription(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VOIDescription() {
    this(imebraJNI.new_VOIDescription__SWIG_0(), true);
  }

  public VOIDescription(VOIDescription source) {
    this(imebraJNI.new_VOIDescription__SWIG_1(VOIDescription.getCPtr(source), source), true);
  }

  public VOIDescription assign(VOIDescription source) {
    return new VOIDescription(imebraJNI.VOIDescription_assign(swigCPtr, this, VOIDescription.getCPtr(source), source), false);
  }

  public VOIDescription(double center, double width, dicomVOIFunction_t function, String description) {
    this(imebraJNI.new_VOIDescription__SWIG_2(center, width, function.swigValue(), description), true);
  }

  public double getCenter() {
    return imebraJNI.VOIDescription_getCenter(swigCPtr, this);
  }

  public double getWidth() {
    return imebraJNI.VOIDescription_getWidth(swigCPtr, this);
  }

  public dicomVOIFunction_t getFunction() {
    return dicomVOIFunction_t.swigToEnum(imebraJNI.VOIDescription_getFunction(swigCPtr, this));
  }

  public String getDescription() {
    return imebraJNI.VOIDescription_getDescription(swigCPtr, this);
  }

}
